<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Case 21.6 Segmenting Consumers of Bath Soap – Chad’s Course Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../../../">
<script src="../../../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../../../index.html">
    <span class="navbar-title">Chad’s Course Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html"> 
<span class="menu-text">test</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link active" data-scroll-target="#load-the-data">Load the data</a></li>
  <li><a href="#step-1" id="toc-step-1" class="nav-link" data-scroll-target="#step-1">Step 1:</a>
  <ul class="collapse">
  <li><a href="#clusters-based-on-purchase-behavior" id="toc-clusters-based-on-purchase-behavior" class="nav-link" data-scroll-target="#clusters-based-on-purchase-behavior">Clusters based on “purchase behavior”</a>
  <ul class="collapse">
  <li><a href="#normalizing-the-data-and-definition-of-helper-functions" id="toc-normalizing-the-data-and-definition-of-helper-functions" class="nav-link" data-scroll-target="#normalizing-the-data-and-definition-of-helper-functions">Normalizing the data and definition of helper functions</a></li>
  <li><a href="#two-clusters" id="toc-two-clusters" class="nav-link" data-scroll-target="#two-clusters">Two clusters</a></li>
  </ul></li>
  <li><a href="#clusters-based-on-basis-for-purchase" id="toc-clusters-based-on-basis-for-purchase" class="nav-link" data-scroll-target="#clusters-based-on-basis-for-purchase">Clusters based on “basis for purchase”</a></li>
  <li><a href="#clusters-based-on-all-of-the-above-variables" id="toc-clusters-based-on-all-of-the-above-variables" class="nav-link" data-scroll-target="#clusters-based-on-all-of-the-above-variables">Clusters based on all of the above variables</a></li>
  </ul></li>
  <li><a href="#step-2" id="toc-step-2" class="nav-link" data-scroll-target="#step-2">Step 2:</a></li>
  <li><a href="#step-3" id="toc-step-3" class="nav-link" data-scroll-target="#step-3">Step 3:</a>
  <ul class="collapse">
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic regression</a></li>
  <li><a href="#decision-tree" id="toc-decision-tree" class="nav-link" data-scroll-target="#decision-tree">Decision tree</a></li>
  <li><a href="#random-forest-classifier" id="toc-random-forest-classifier" class="nav-link" data-scroll-target="#random-forest-classifier">Random forest classifier</a></li>
  <li><a href="#bagging-classifier" id="toc-bagging-classifier" class="nav-link" data-scroll-target="#bagging-classifier">Bagging classifier</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s next?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Case 21.6 Segmenting Consumers of Bath Soap</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<ol start="3" type="a">
<li>2019 Galit Shmueli, Peter C. Bruce, Peter Gedeck</li>
</ol>
<p>Case study included in</p>
<p><em>Data Mining for Business Analytics: Concepts, Techniques, and Applications in Python</em> (First Edition) Galit Shmueli, Peter C. Bruce, Peter Gedeck, and Nitin R. Patel. 2019.</p>
</blockquote>
<div id="cell-2" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> KMeans</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> BaggingClassifier</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pylab <span class="im">as</span> plt</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> classificationSummary, gainsChart</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display_html</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> Path(<span class="st">'.'</span>).resolve().parent <span class="op">/</span> <span class="st">'data'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">Load the data</h2>
<div id="cell-4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bathSoap_df <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'BathSoapHousehold.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bathSoap_df.shape)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>bathSoap_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(600, 46)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Member id</th>
<th data-quarto-table-cell-role="th">SEC</th>
<th data-quarto-table-cell-role="th">FEH</th>
<th data-quarto-table-cell-role="th">MT</th>
<th data-quarto-table-cell-role="th">SEX</th>
<th data-quarto-table-cell-role="th">AGE</th>
<th data-quarto-table-cell-role="th">EDU</th>
<th data-quarto-table-cell-role="th">HS</th>
<th data-quarto-table-cell-role="th">CHILD</th>
<th data-quarto-table-cell-role="th">CS</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">PropCat 6</th>
<th data-quarto-table-cell-role="th">PropCat 7</th>
<th data-quarto-table-cell-role="th">PropCat 8</th>
<th data-quarto-table-cell-role="th">PropCat 9</th>
<th data-quarto-table-cell-role="th">PropCat 10</th>
<th data-quarto-table-cell-role="th">PropCat 11</th>
<th data-quarto-table-cell-role="th">PropCat 12</th>
<th data-quarto-table-cell-role="th">PropCat 13</th>
<th data-quarto-table-cell-role="th">PropCat 14</th>
<th data-quarto-table-cell-role="th">PropCat 15</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1010010</td>
<td>4</td>
<td>3</td>
<td>10</td>
<td>1</td>
<td>4</td>
<td>4</td>
<td>2</td>
<td>4</td>
<td>1</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.028037</td>
<td>0.0</td>
<td>0.130841</td>
<td>0.339564</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1010020</td>
<td>3</td>
<td>2</td>
<td>10</td>
<td>2</td>
<td>2</td>
<td>4</td>
<td>4</td>
<td>2</td>
<td>1</td>
<td>...</td>
<td>0.347048</td>
<td>0.026834</td>
<td>0.016100</td>
<td>0.014311</td>
<td>0.0</td>
<td>0.059034</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.080501</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1014020</td>
<td>2</td>
<td>3</td>
<td>10</td>
<td>2</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>4</td>
<td>1</td>
<td>...</td>
<td>0.121212</td>
<td>0.033550</td>
<td>0.010823</td>
<td>0.008658</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.016234</td>
<td>0.0</td>
<td>0.561688</td>
<td>0.003247</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1014030</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>5</td>
<td>0</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.600000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1014190</td>
<td>4</td>
<td>1</td>
<td>10</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>4</td>
<td>3</td>
<td>1</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.048193</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.144578</td>
<td>0.000000</td>
</tr>
</tbody>
</table>

<p>5 rows × 46 columns</p>
</div>
</div>
</div>
</section>
<section id="step-1" class="level1">
<h1>Step 1:</h1>
<p>Use <span class="math inline">\(k\)</span>-means clustering to identify clusters of households based on:</p>
<ol type="1">
<li>The variables that describe purchase behavior (including brand loyalty)</li>
<li>The variables that describe the basis for purchase</li>
<li>The variables that describe both purchase behavior and basis of purchase</li>
</ol>
<p>Note 1: How should <span class="math inline">\(k\)</span> be chosen? Think about how the clusters would be used. It is likely that the marketing efforts would support two to five different promotional approaches.</p>
<p>Note 2: How should the percentages of total purchases comprised by various brands be treated? Isn’t a customer who buys all brand A just as loyal as a customer who buys all brand B? What will be the effect on any distance measure of using the brand share variables as is? Consider using a single derived variable.</p>
<p>We look first at clusters based on purchase behavior, then clusters based on the basis for purchase, then clusters based on both. The complexity of marketing to 5 segments would probably not be supported by clustering just based on purchase behavior, or clustering just based on basis for purchase, so we will look at 2-3 clusters for those variables, and more when we cluster using both sets of variables.</p>
<p>In choosing 𝑘 , we would seek a 𝑘 that produces clusters that are distinct and separate from one another, in ways (variables) that are translatable into marketing actions. The variables we have been asked to consider are those that relate to purchase behavior (volume and frequency of purchase, brand loyalty), and a separate set that relate to the basis for purchase (response to promotions, pricing, and selling proposition).</p>
<div id="cell-6" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group columns into sets for further analysis</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>demographicIndicators <span class="op">=</span> bathSoap_df.columns[<span class="dv">1</span>:<span class="dv">11</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>purchaseIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">11</span>:<span class="dv">19</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>withinPromotionIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">19</span>:<span class="dv">22</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>brandIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">22</span>:<span class="dv">30</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>otherBrandIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">30</span>:<span class="dv">31</span>]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>priceCategoryIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">31</span>:<span class="dv">35</span>]</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>sellingPropertyIndicator <span class="op">=</span> bathSoap_df.columns[<span class="dv">35</span>:<span class="dv">46</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Demographic'</span>, demographicIndicators)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Purchase'</span>, purchaseIndicator)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Promotion'</span>, withinPromotionIndicator)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Brand'</span>, brandIndicator)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Other brand'</span>, otherBrandIndicator)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Price category'</span>, priceCategoryIndicator)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Selling property'</span>, sellingPropertyIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Demographic Index(['SEC', 'FEH', 'MT', 'SEX', 'AGE', 'EDU', 'HS', 'CHILD', 'CS',
       'Affluence Index'],
      dtype='object')
Purchase Index(['No. of Brands', 'Brand Runs', 'Total Volume', 'No. of  Trans', 'Value',
       'Trans / Brand Runs', 'Vol/Tran', 'Avg. Price '],
      dtype='object')
Promotion Index(['Pur Vol No Promo - %', 'Pur Vol Promo 6 %', 'Pur Vol Other Promo %'], dtype='object')
Brand Index(['Br. Cd. 57, 144', 'Br. Cd. 55', 'Br. Cd. 272', 'Br. Cd. 286',
       'Br. Cd. 24', 'Br. Cd. 481', 'Br. Cd. 352', 'Br. Cd. 5'],
      dtype='object')
Other brand Index(['Others 999'], dtype='object')
Price category Index(['Pr Cat 1', 'Pr Cat 2', 'Pr Cat 3', 'Pr Cat 4'], dtype='object')
Selling property Index(['PropCat 5', 'PropCat 6', 'PropCat 7', 'PropCat 8', 'PropCat 9',
       'PropCat 10', 'PropCat 11', 'PropCat 12', 'PropCat 13', 'PropCat 14',
       'PropCat 15'],
      dtype='object')</code></pre>
</div>
</div>
<section id="clusters-based-on-purchase-behavior" class="level2">
<h2 class="anchored" data-anchor-id="clusters-based-on-purchase-behavior">Clusters based on “purchase behavior”</h2>
<p>Note: Some thought is needed about brand loyalty. For brand loyalty indicators, we have data on</p>
<ol type="1">
<li>percent of purchases devoted to major brands (i.e.&nbsp;is a customer a total devotee of brand A?), <code>brandIndicator</code></li>
<li>a catch-all variable for percent of purchases devoted to other smaller brands (to reduce complexity of analysis), and <code>otherBrandIndicator</code></li>
<li>a derived variable that indicates the maximum share devoted to any one brand.</li>
</ol>
<p>Since CRISA is compiling this data for general marketing use, and not on behalf of one particular brand, we can say a customer who is fully devoted to brand A is similar to a customer fully devoted to brand B - both are fully loyal customers in their behavior. But if we include all the brand shares in the clustering, the analysis will treat those two customers as very different.</p>
<ol type="1">
<li>Number of different brands: <code>No. of Brands</code></li>
<li>Switching between brands: <code>Brand Runs</code></li>
<li>Proportion of purchases that go to different brands: We use the information in the <code>brandIndicator</code> to determine the maximum proportion a customer spends on one brand (new variable <code>maxBrandIndicator</code>)</li>
</ol>
<p>We derive the value of <code>maxBrandIndicator</code> by taking the maximum of all specific brand indicators.</p>
<div id="cell-8" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bathSoap_df[<span class="st">'maxBrandIndicator'</span>] <span class="op">=</span> bathSoap_df[brandIndicator].<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For this analysis, we use all <code>purchaseIndicator</code>, <code>maxBrandIndicator</code> and <code>otherBrandIndicator</code> as a description of the customers purchase behavior</p>
<div id="cell-10" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>behaviorIndicator <span class="op">=</span> <span class="bu">list</span>(purchaseIndicator) <span class="op">+</span> <span class="bu">list</span>(otherBrandIndicator) <span class="op">+</span> [<span class="st">'maxBrandIndicator'</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(behaviorIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['No. of Brands', 'Brand Runs', 'Total Volume', 'No. of  Trans', 'Value', 'Trans / Brand Runs', 'Vol/Tran', 'Avg. Price ', 'Others 999', 'maxBrandIndicator']</code></pre>
</div>
</div>
<section id="normalizing-the-data-and-definition-of-helper-functions" class="level3">
<h3 class="anchored" data-anchor-id="normalizing-the-data-and-definition-of-helper-functions">Normalizing the data and definition of helper functions</h3>
<div id="cell-12" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize the data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>bathSoap_df_norm <span class="op">=</span> (bathSoap_df <span class="op">-</span> bathSoap_df.mean())<span class="op">/</span>bathSoap_df.std()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clusterSizes(kmeans):</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series(kmeans.labels_).value_counts().sort_index()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clusterCenters(kmeans, indicator):</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> bathSoap_df_norm[indicator].groupby(kmeans.labels_).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="two-clusters" class="level3">
<h3 class="anchored" data-anchor-id="two-clusters">Two clusters</h3>
<div id="cell-14" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[behaviorIndicator])</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>clusterCenters(clusters, behaviorIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    317
1    283
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">No. of Brands</th>
<th data-quarto-table-cell-role="th">Brand Runs</th>
<th data-quarto-table-cell-role="th">Total Volume</th>
<th data-quarto-table-cell-role="th">No. of Trans</th>
<th data-quarto-table-cell-role="th">Value</th>
<th data-quarto-table-cell-role="th">Trans / Brand Runs</th>
<th data-quarto-table-cell-role="th">Vol/Tran</th>
<th data-quarto-table-cell-role="th">Avg. Price</th>
<th data-quarto-table-cell-role="th">Others 999</th>
<th data-quarto-table-cell-role="th">maxBrandIndicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.483611</td>
<td>0.632865</td>
<td>0.158222</td>
<td>0.522115</td>
<td>0.306960</td>
<td>-0.261283</td>
<td>-0.285383</td>
<td>0.279689</td>
<td>0.488928</td>
<td>-0.588026</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.541712</td>
<td>-0.708898</td>
<td>-0.177232</td>
<td>-0.584843</td>
<td>-0.343838</td>
<td>0.292674</td>
<td>0.319669</td>
<td>-0.313291</td>
<td>-0.547669</td>
<td>0.658673</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comment: The two clusters are well-separated on everything, except transaction volume. - Cluster 0 (n=317) is high activity &amp; value, with low loyalty. - Cluster 1 (n=283) is the reverse.</p>
<p>(“Value” here is the meaning attached to the variable - total dollar value of purchases, not some broader meaning.) Note: Due to the randomization element in the k-means process, different runs can produce different cluster results.</p>
<div id="cell-16" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[behaviorIndicator])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>clusterCenters(clusters, behaviorIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    166
1    259
2    175
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">No. of Brands</th>
<th data-quarto-table-cell-role="th">Brand Runs</th>
<th data-quarto-table-cell-role="th">Total Volume</th>
<th data-quarto-table-cell-role="th">No. of Trans</th>
<th data-quarto-table-cell-role="th">Value</th>
<th data-quarto-table-cell-role="th">Trans / Brand Runs</th>
<th data-quarto-table-cell-role="th">Vol/Tran</th>
<th data-quarto-table-cell-role="th">Avg. Price</th>
<th data-quarto-table-cell-role="th">Others 999</th>
<th data-quarto-table-cell-role="th">maxBrandIndicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.950737</td>
<td>1.099320</td>
<td>0.635975</td>
<td>1.082139</td>
<td>0.767309</td>
<td>-0.254805</td>
<td>-0.190209</td>
<td>0.127343</td>
<td>0.254809</td>
<td>-0.477311</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.275933</td>
<td>-0.215651</td>
<td>-0.532365</td>
<td>-0.415564</td>
<td>-0.454992</td>
<td>-0.247321</td>
<td>-0.273599</td>
<td>0.228323</td>
<td>0.599030</td>
<td>-0.532205</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-0.493460</td>
<td>-0.723619</td>
<td>0.184632</td>
<td>-0.411452</td>
<td>-0.054460</td>
<td>0.607736</td>
<td>0.585353</td>
<td>-0.458712</td>
<td>-1.128269</td>
<td>1.240427</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comment: - Cluster 0 (n=166) is not at all loyal, favoring many brands, and of high value. - Cluster 1 (n=259) is also not very loyal, but may be of the least interest since its customers have the lowest value. - Cluster 2 (n=175) is highly loyal, favoring main brands and bigger individual purchases, with middling overall value.</p>
</section>
</section>
<section id="clusters-based-on-basis-for-purchase" class="level2">
<h2 class="anchored" data-anchor-id="clusters-based-on-basis-for-purchase">Clusters based on “basis for purchase”</h2>
<p>The variables used are: <code>Pur Vol No Promo - %</code>, <code>Pur Vol Promo 6 %</code>, <code>Pur Vol Other Promo %</code>, all price categories, selling propositions 5 and 14 (most people seemed to be responding to one or the other of these promotions/propositions).</p>
<div id="cell-19" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>purchaseBasisIndicator <span class="op">=</span> <span class="bu">list</span>(withinPromotionIndicator) <span class="op">+</span> <span class="bu">list</span>(priceCategoryIndicator) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>purchaseBasisIndicator.extend([<span class="st">'PropCat 5'</span>, <span class="st">'PropCat 14'</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(purchaseBasisIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['Pur Vol No Promo - %', 'Pur Vol Promo 6 %', 'Pur Vol Other Promo %', 'Pr Cat 1', 'Pr Cat 2', 'Pr Cat 3', 'Pr Cat 4', 'PropCat 5', 'PropCat 14']</code></pre>
</div>
</div>
<div id="cell-20" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[purchaseBasisIndicator])</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>clusterCenters(clusters, purchaseBasisIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0     77
1    523
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pur Vol No Promo - %</th>
<th data-quarto-table-cell-role="th">Pur Vol Promo 6 %</th>
<th data-quarto-table-cell-role="th">Pur Vol Other Promo %</th>
<th data-quarto-table-cell-role="th">Pr Cat 1</th>
<th data-quarto-table-cell-role="th">Pr Cat 2</th>
<th data-quarto-table-cell-role="th">Pr Cat 3</th>
<th data-quarto-table-cell-role="th">Pr Cat 4</th>
<th data-quarto-table-cell-role="th">PropCat 5</th>
<th data-quarto-table-cell-role="th">PropCat 14</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.205410</td>
<td>-0.402586</td>
<td>0.179079</td>
<td>-0.791774</td>
<td>-1.134101</td>
<td>2.387450</td>
<td>-0.334659</td>
<td>-1.105730</td>
<td>2.391835</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.030242</td>
<td>0.059272</td>
<td>-0.026365</td>
<td>0.116571</td>
<td>0.166971</td>
<td>-0.351498</td>
<td>0.049271</td>
<td>0.162794</td>
<td>-0.352144</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comment: The two clusters are well-separated across most variables. - Cluster 0 (n=77) is notable for its responsiveness to price category 3 and selling proposition 14 coupled with aversion to price categories 1 and 2, and selling proposition 5. - Cluster 1 (n=523) shows a less clear profile</p>
<div id="cell-22" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[purchaseBasisIndicator])</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>clusterCenters(clusters, purchaseBasisIndicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0     74
1    429
2     97
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pur Vol No Promo - %</th>
<th data-quarto-table-cell-role="th">Pur Vol Promo 6 %</th>
<th data-quarto-table-cell-role="th">Pur Vol Other Promo %</th>
<th data-quarto-table-cell-role="th">Pr Cat 1</th>
<th data-quarto-table-cell-role="th">Pr Cat 2</th>
<th data-quarto-table-cell-role="th">Pr Cat 3</th>
<th data-quarto-table-cell-role="th">Pr Cat 4</th>
<th data-quarto-table-cell-role="th">PropCat 5</th>
<th data-quarto-table-cell-role="th">PropCat 14</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.256679</td>
<td>-0.434717</td>
<td>0.135482</td>
<td>-0.802892</td>
<td>-1.152356</td>
<td>2.432767</td>
<td>-0.352060</td>
<td>-1.136908</td>
<td>2.436529</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.349656</td>
<td>-0.287933</td>
<td>-0.208460</td>
<td>0.062932</td>
<td>0.258829</td>
<td>-0.336154</td>
<td>-0.042901</td>
<td>0.195635</td>
<td>-0.335935</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.742234</td>
<td>1.605076</td>
<td>0.818594</td>
<td>0.334189</td>
<td>-0.265602</td>
<td>-0.369225</td>
<td>0.458320</td>
<td>0.002103</td>
<td>-0.373063</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comment: - Cluster 0 (n=74) has the same profile as cluster 0 in the two cluster case. - Cluster 1 (n=429) corresponds mainly to cluster 1 in the two cluster case. - Cluster 2 (n=97) needs promostions, likes price categories 1 and 4, and is not responsive to the two selling propositions.</p>
</section>
<section id="clusters-based-on-all-of-the-above-variables" class="level2">
<h2 class="anchored" data-anchor-id="clusters-based-on-all-of-the-above-variables">Clusters based on all of the above variables</h2>
<div id="cell-25" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>combinedIndicator <span class="op">=</span> behaviorIndicator <span class="op">+</span> purchaseBasisIndicator </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[combinedIndicator])</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>clusterCenters(clusters, combinedIndicator).transpose()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    528
1     72
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">No. of Brands</td>
<td>0.076539</td>
<td>-0.561285</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Brand Runs</td>
<td>0.107685</td>
<td>-0.789690</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Total Volume</td>
<td>-0.017671</td>
<td>0.129590</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. of Trans</td>
<td>0.057712</td>
<td>-0.423219</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Value</td>
<td>0.070433</td>
<td>-0.516510</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Trans / Brand Runs</td>
<td>-0.143673</td>
<td>1.053602</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Vol/Tran</td>
<td>-0.074915</td>
<td>0.549376</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Avg. Price</td>
<td>0.178255</td>
<td>-1.307201</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Others 999</td>
<td>0.171574</td>
<td>-1.258207</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">maxBrandIndicator</td>
<td>-0.193782</td>
<td>1.421067</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pur Vol No Promo - %</td>
<td>-0.026127</td>
<td>0.191600</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pur Vol Promo 6 %</td>
<td>0.056392</td>
<td>-0.413540</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pur Vol Other Promo %</td>
<td>-0.029475</td>
<td>0.216152</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pr Cat 1</td>
<td>0.109357</td>
<td>-0.801955</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pr Cat 2</td>
<td>0.160177</td>
<td>-1.174631</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pr Cat 3</td>
<td>-0.332833</td>
<td>2.440774</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pr Cat 4</td>
<td>0.044785</td>
<td>-0.328422</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">PropCat 5</td>
<td>0.155090</td>
<td>-1.137330</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">PropCat 14</td>
<td>-0.333261</td>
<td>2.443912</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comment: The two clusters are separated on almost all variables, Value being an important exception.</p>
<div id="cell-27" class="cell" data-scrolled="true" data-execution_count="13">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clusterDemographics(kmeans):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> bathSoap_df[demographicIndicators].groupby(kmeans.labels_).mean()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>clusterDemographics(clusters).transpose()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">SEC</td>
<td>2.375000</td>
<td>3.416667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">FEH</td>
<td>2.049242</td>
<td>2.041667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">MT</td>
<td>8.250000</td>
<td>7.652778</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">SEX</td>
<td>1.763258</td>
<td>1.555556</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">AGE</td>
<td>3.246212</td>
<td>2.972222</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">EDU</td>
<td>4.268939</td>
<td>2.388889</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">HS</td>
<td>4.198864</td>
<td>4.138889</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CHILD</td>
<td>3.202652</td>
<td>3.458333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CS</td>
<td>0.937500</td>
<td>0.888889</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Affluence Index</td>
<td>18.159091</td>
<td>8.666667</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Cluster 1 (n=72) is the more loyal, with lower socioeconomic status, educational level, and affluence.</p>
<div id="cell-29" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> display_side_by_side(<span class="op">*</span>args):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    html_str <span class="op">=</span> <span class="st">''</span>.join(df.to_html() <span class="cf">for</span> df <span class="kw">in</span> args)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    display_html(html_str.replace(<span class="st">'table'</span>,<span class="st">'table style="display:inline"'</span>),raw<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>combinedIndicator <span class="op">=</span> behaviorIndicator <span class="op">+</span> purchaseBasisIndicator </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[combinedIndicator])</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>display_side_by_side(clusterCenters(clusters, combinedIndicator).transpose(),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                     clusterDemographics(clusters).transpose())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0     72
1    248
2    280
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<table style="display:inline" class="dataframe table table-sm table-striped small">
  <thead>
    <tr>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>No. of Brands</th>
      <td>-0.508532</td>
      <td>-0.346872</td>
      <td>0.437995</td>
    </tr>
    <tr>
      <th>Brand Runs</th>
      <td>-0.761636</td>
      <td>-0.474887</td>
      <td>0.616463</td>
    </tr>
    <tr>
      <th>Total Volume</th>
      <td>0.137098</td>
      <td>0.043343</td>
      <td>-0.073643</td>
    </tr>
    <tr>
      <th>No. of  Trans</th>
      <td>-0.390544</td>
      <td>-0.412782</td>
      <td>0.466032</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>-0.513577</td>
      <td>-0.042678</td>
      <td>0.169863</td>
    </tr>
    <tr>
      <th>Trans / Brand Runs</th>
      <td>1.004705</td>
      <td>-0.018763</td>
      <td>-0.241734</td>
    </tr>
    <tr>
      <th>Vol/Tran</th>
      <td>0.520628</td>
      <td>0.373779</td>
      <td>-0.464937</td>
    </tr>
    <tr>
      <th>Avg. Price</th>
      <td>-1.310393</td>
      <td>-0.196607</td>
      <td>0.511096</td>
    </tr>
    <tr>
      <th>Others 999</th>
      <td>-1.248331</td>
      <td>-0.225977</td>
      <td>0.521151</td>
    </tr>
    <tr>
      <th>maxBrandIndicator</th>
      <td>1.396638</td>
      <td>0.288194</td>
      <td>-0.614393</td>
    </tr>
    <tr>
      <th>Pur Vol No Promo - %</th>
      <td>0.196872</td>
      <td>0.283258</td>
      <td>-0.301510</td>
    </tr>
    <tr>
      <th>Pur Vol Promo 6 %</th>
      <td>-0.413540</td>
      <td>-0.299317</td>
      <td>0.371448</td>
    </tr>
    <tr>
      <th>Pur Vol Other Promo %</th>
      <td>0.207402</td>
      <td>-0.083541</td>
      <td>0.020661</td>
    </tr>
    <tr>
      <th>Pr Cat 1</th>
      <td>-0.797347</td>
      <td>-0.451972</td>
      <td>0.605350</td>
    </tr>
    <tr>
      <th>Pr Cat 2</th>
      <td>-1.204639</td>
      <td>0.550190</td>
      <td>-0.177547</td>
    </tr>
    <tr>
      <th>Pr Cat 3</th>
      <td>2.470385</td>
      <td>-0.293348</td>
      <td>-0.375420</td>
    </tr>
    <tr>
      <th>Pr Cat 4</th>
      <td>-0.327801</td>
      <td>0.178150</td>
      <td>-0.073498</td>
    </tr>
    <tr>
      <th>PropCat 5</th>
      <td>-1.126918</td>
      <td>0.559757</td>
      <td>-0.206006</td>
    </tr>
    <tr>
      <th>PropCat 14</th>
      <td>2.473743</td>
      <td>-0.294432</td>
      <td>-0.375323</td>
    </tr>
  </tbody>
</table><table style="display:inline" class="dataframe table table-sm table-striped small">
  <thead>
    <tr>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>SEC</th>
      <td>3.416667</td>
      <td>2.641129</td>
      <td>2.139286</td>
    </tr>
    <tr>
      <th>FEH</th>
      <td>2.041667</td>
      <td>2.008065</td>
      <td>2.085714</td>
    </tr>
    <tr>
      <th>MT</th>
      <td>7.652778</td>
      <td>7.979839</td>
      <td>8.489286</td>
    </tr>
    <tr>
      <th>SEX</th>
      <td>1.555556</td>
      <td>1.693548</td>
      <td>1.825000</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>3.000000</td>
      <td>3.229839</td>
      <td>3.253571</td>
    </tr>
    <tr>
      <th>EDU</th>
      <td>2.347222</td>
      <td>3.802419</td>
      <td>4.692857</td>
    </tr>
    <tr>
      <th>HS</th>
      <td>4.125000</td>
      <td>4.193548</td>
      <td>4.207143</td>
    </tr>
    <tr>
      <th>CHILD</th>
      <td>3.486111</td>
      <td>3.262097</td>
      <td>3.142857</td>
    </tr>
    <tr>
      <th>CS</th>
      <td>0.888889</td>
      <td>0.899194</td>
      <td>0.971429</td>
    </tr>
    <tr>
      <th>Affluence Index</th>
      <td>8.694444</td>
      <td>14.895161</td>
      <td>21.042857</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<p>Comment: - Cluster 0: (n=72) Highly loyal, low value, highly responsive to price category 3 and selling proposition 14. - Cluster 1: (n=252) Responsive to price category 2 and selling proposition 5, otherwise somewhat middling. - Cluster 2: (n=278) Low brand loyalty, responsive to price category 1</p>
<div id="cell-31" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>combinedIndicator <span class="op">=</span> behaviorIndicator <span class="op">+</span> purchaseBasisIndicator </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">4</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[combinedIndicator])</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>display_side_by_side(clusterCenters(clusters, combinedIndicator).transpose(),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                     clusterDemographics(clusters).transpose())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    109
1    201
2     70
3    220
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<table style="display:inline" class="dataframe table table-sm table-striped small">
  <thead>
    <tr>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>No. of Brands</th>
      <td>-0.414643</td>
      <td>0.837833</td>
      <td>-0.583893</td>
      <td>-0.374254</td>
    </tr>
    <tr>
      <th>Brand Runs</th>
      <td>-0.318502</td>
      <td>0.973787</td>
      <td>-0.800569</td>
      <td>-0.477157</td>
    </tr>
    <tr>
      <th>Total Volume</th>
      <td>-0.651976</td>
      <td>0.290887</td>
      <td>0.083386</td>
      <td>0.030727</td>
    </tr>
    <tr>
      <th>No. of  Trans</th>
      <td>-0.426788</td>
      <td>0.824516</td>
      <td>-0.433421</td>
      <td>-0.403947</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>-0.218712</td>
      <td>0.388624</td>
      <td>-0.555616</td>
      <td>-0.069913</td>
    </tr>
    <tr>
      <th>Trans / Brand Runs</th>
      <td>-0.140179</td>
      <td>-0.299278</td>
      <td>1.037226</td>
      <td>0.012857</td>
    </tr>
    <tr>
      <th>Vol/Tran</th>
      <td>-0.458972</td>
      <td>-0.360995</td>
      <td>0.513840</td>
      <td>0.393724</td>
    </tr>
    <tr>
      <th>Avg. Price</th>
      <td>1.358148</td>
      <td>0.063462</td>
      <td>-1.318253</td>
      <td>-0.311438</td>
    </tr>
    <tr>
      <th>Others 999</th>
      <td>0.514018</td>
      <td>0.368089</td>
      <td>-1.264136</td>
      <td>-0.188747</td>
    </tr>
    <tr>
      <th>maxBrandIndicator</th>
      <td>-0.418273</td>
      <td>-0.552509</td>
      <td>1.421065</td>
      <td>0.259871</td>
    </tr>
    <tr>
      <th>Pur Vol No Promo - %</th>
      <td>0.187409</td>
      <td>-0.477946</td>
      <td>0.210216</td>
      <td>0.276930</td>
    </tr>
    <tr>
      <th>Pur Vol Promo 6 %</th>
      <td>-0.175746</td>
      <td>0.584703</td>
      <td>-0.436005</td>
      <td>-0.308403</td>
    </tr>
    <tr>
      <th>Pur Vol Other Promo %</th>
      <td>-0.084062</td>
      <td>0.038058</td>
      <td>0.214271</td>
      <td>-0.061299</td>
    </tr>
    <tr>
      <th>Pr Cat 1</th>
      <td>1.641899</td>
      <td>0.045993</td>
      <td>-0.797226</td>
      <td>-0.601845</td>
    </tr>
    <tr>
      <th>Pr Cat 2</th>
      <td>-0.818168</td>
      <td>0.140268</td>
      <td>-1.220714</td>
      <td>0.665620</td>
    </tr>
    <tr>
      <th>Pr Cat 3</th>
      <td>-0.479027</td>
      <td>-0.267756</td>
      <td>2.495499</td>
      <td>-0.312055</td>
    </tr>
    <tr>
      <th>Pr Cat 4</th>
      <td>-0.406199</td>
      <td>0.079000</td>
      <td>-0.336964</td>
      <td>0.236292</td>
    </tr>
    <tr>
      <th>PropCat 5</th>
      <td>-0.358174</td>
      <td>-0.078526</td>
      <td>-1.142977</td>
      <td>0.612878</td>
    </tr>
    <tr>
      <th>PropCat 14</th>
      <td>-0.472507</td>
      <td>-0.270906</td>
      <td>2.498321</td>
      <td>-0.313305</td>
    </tr>
  </tbody>
</table><table style="display:inline" class="dataframe table table-sm table-striped small">
  <thead>
    <tr>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>SEC</th>
      <td>1.779817</td>
      <td>2.368159</td>
      <td>3.400000</td>
      <td>2.690909</td>
    </tr>
    <tr>
      <th>FEH</th>
      <td>1.669725</td>
      <td>2.233831</td>
      <td>2.042857</td>
      <td>2.068182</td>
    </tr>
    <tr>
      <th>MT</th>
      <td>6.733945</td>
      <td>9.024876</td>
      <td>7.671429</td>
      <td>8.281818</td>
    </tr>
    <tr>
      <th>SEX</th>
      <td>1.477064</td>
      <td>1.920398</td>
      <td>1.542857</td>
      <td>1.763636</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>3.165138</td>
      <td>3.323383</td>
      <td>3.014286</td>
      <td>3.200000</td>
    </tr>
    <tr>
      <th>EDU</th>
      <td>4.165138</td>
      <td>4.626866</td>
      <td>2.357143</td>
      <td>3.986364</td>
    </tr>
    <tr>
      <th>HS</th>
      <td>3.045872</td>
      <td>4.681592</td>
      <td>3.914286</td>
      <td>4.400000</td>
    </tr>
    <tr>
      <th>CHILD</th>
      <td>3.550459</td>
      <td>3.044776</td>
      <td>3.514286</td>
      <td>3.159091</td>
    </tr>
    <tr>
      <th>CS</th>
      <td>0.743119</td>
      <td>1.044776</td>
      <td>0.871429</td>
      <td>0.940909</td>
    </tr>
    <tr>
      <th>Affluence Index</th>
      <td>18.018349</td>
      <td>20.930348</td>
      <td>8.542857</td>
      <td>15.650000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<p>Comment: - Cluster 0 (n=109) is characterized by low volume, low loyalty, and sensitivity to promotions and price (responsive to cat. 1, unresponsive to 2 and 3), and unmoved by selling proposition. Demographically, it is affluent, of high socio-economic status, and has relatively small family size. - Cluster 1 (n=201) is distinguished mostly by the purchase behavior variables - it has low brand loyalty together with high value, volume and frequency. The brand switching seems to be intrinsic - this group is not particularly responsive to promotions, pricing or selling propositions. Demographically it is relatively affluent and educated. - Cluster 2 (n=70) stands out in both groups of variables - it has high loyalty, low value and price per purchase, and very differential response to price (unresponsive to categories 1, 2 and 4, highly responsive to category 3), and selling proposition (unresponsive to #5, highly responsive to #14). Demographically it has low affluence and education. - Cluster 3 (n=220) is a “gray” cluster, it is not characterized by very extreme/distinctive values across all variables, but is responsive to price category 2 and selling proposition 5 (similar to cluster 1 in the 3-cluster analysis). Demographically it is relatively affluent and educated.</p>
</section>
</section>
<section id="step-2" class="level1">
<h1>Step 2:</h1>
<p>Select what you think is the best segmentation and comment on the characteristics (demographic, brand loyalty, and basis for purchase) of these clusters. (This information would be used to guide the development of advertising and promotional campaigns.)</p>
<p>There is no single “right” approach to clustering; different approaches are feasible depending on different marketing purposes. CRISA is a marketing agency and owns the data, which it collected at considerable expense, so it will want to be able to use both the data and the segmentation analysis in different ways for different clients. Here are just a few possible marketing approaches:</p>
<ol type="1">
<li>Establishing named customer “personas,” corresponding to the cluster segments, for use by a client’s sales and marketing teams.</li>
<li>Establishing named customer “personas,” corresponding to the cluster segments, for use by CRISA in providing marketing services to clients.</li>
<li>“Capture affluent market share” campaign for a client who wants to target more affluent consumers who are not wedded to their current brand, and secure more brand share.</li>
<li>“Down market” campaign for a data-poor client to build a “value” brand for less affluent consumers, much as Dollar General has done in the U.S.</li>
</ol>
<p>note: The difference between #1 and #2 is that #1, being confined to a single client, can use that client’s customer data to refine and do more analysis. #2 would have to rely on the data collected by CRISA.</p>
</section>
<section id="step-3" class="level1">
<h1>Step 3:</h1>
<p>Develop a model that classifies the data into these segments. Since this information would most likely be used in targeting direct-mail promotions, it would be useful to select a market segment that would be defined as a <em>success</em> in the classification model.</p>
<p>This “down market” scenario is the one we will explore further to develop a predictive model, and classify people into either “value conscious” or not. “Data poor” means that the client has, or can get, demographic data on their customers, but not detailed purchase data (particularly involving other brands). So a predictive model is to be built using just demographic data. We will look at the results of clustering into two segments based on CRISA’s own detailed purchase data, then classify people into those two segments.</p>
<p>Recall our characterization of the two segments:</p>
<p>Comment: The two clusters are separated on almost all variables, Value being an important exception. Cluster 1 (n=72) is the more loyal, with lower socioeconomic status and affluence.</p>
<p>So our “success” category is cluster 1, the less affluent group, lower socioeconomic group, which also turns out to be highly loyal and, as it happens, spends roughly as much as the more affluent group. This is a promising group around which to build a down-market brand strategy.</p>
<p>To build the model, we will be able to only use demographic information. CRISA will not have the detailed purchase information for its client’s customers.</p>
<div id="cell-35" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(bathSoap_df_norm[combinedIndicator])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clusterSizes(clusters))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>modelData_df <span class="op">=</span> bathSoap_df[demographicIndicators].copy()</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>modelData_df <span class="op">=</span> pd.get_dummies(modelData_df, columns<span class="op">=</span>[<span class="st">'MT'</span>, <span class="st">'FEH'</span>])</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>modelData_df[<span class="st">'y'</span>] <span class="op">=</span> [<span class="dv">1</span> <span class="cf">if</span> label <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="dv">0</span> <span class="cf">for</span> label <span class="kw">in</span> clusters.labels_]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>train_df, valid_df <span class="op">=</span> train_test_split(modelData_df, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>train_X, train_y <span class="op">=</span> train_df.drop(columns<span class="op">=</span>[<span class="st">'y'</span>]), train_df[<span class="st">'y'</span>]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>valid_X, valid_y <span class="op">=</span> valid_df.drop(columns<span class="op">=</span>[<span class="st">'y'</span>]), valid_df[<span class="st">'y'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    528
1     72
dtype: int64</code></pre>
</div>
</div>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic regression</h3>
<div id="cell-37" class="cell" data-scrolled="false" data-execution_count="17">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model.fit(train_X, train_y)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>model_pred <span class="op">=</span> model.predict_proba(valid_X)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'actual'</span>: valid_y,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'predicted'</span>: model.predict(valid_X),</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>classificationSummary(result.actual, result.predicted)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, figsize<span class="op">=</span>[<span class="dv">5</span>, <span class="dv">5</span>])</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>nx <span class="op">=</span> <span class="bu">round</span>(valid_df.shape[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.2</span>)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>ny <span class="op">=</span> <span class="bu">sum</span>(result.actual[<span class="dv">0</span>:nx])</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>ax.plot([nx, nx,<span class="dv">0</span>], [<span class="dv">0</span>, ny, ny])</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in validaton set'</span>, valid_y.<span class="bu">sum</span>())</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in 20% top-ranked'</span>, ny)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ratio </span><span class="sc">{</span>ny <span class="op">/</span> valid_y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8833)

       Prediction
Actual   0   1
     0 207   2
     1  26   5
Number of customers of interest in validaton set 31
Number of customers of interest in 20% top-ranked 18
Ratio 0.58</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Case 21.6 Segmenting Consumers of Bath Soap_files/figure-html/cell-18-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="decision-tree" class="level3">
<h3 class="anchored" data-anchor-id="decision-tree">Decision tree</h3>
<div id="cell-39" class="cell" data-scrolled="false" data-execution_count="18">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>model.fit(train_X, train_y)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>model_pred <span class="op">=</span> model.predict_proba(valid_X)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'actual'</span>: valid_y,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'predicted'</span>: model.predict(valid_X),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>classificationSummary(result.actual, result.predicted)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, figsize<span class="op">=</span>[<span class="dv">5</span>, <span class="dv">5</span>])</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>nx <span class="op">=</span> <span class="bu">round</span>(valid_df.shape[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.2</span>)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>ny <span class="op">=</span> <span class="bu">sum</span>(result.actual[<span class="dv">0</span>:nx])</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>ax.plot([nx, nx,<span class="dv">0</span>], [<span class="dv">0</span>, ny, ny])</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in validaton set'</span>, valid_y.<span class="bu">sum</span>())</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in 20% top-ranked'</span>, ny)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ratio </span><span class="sc">{</span>ny <span class="op">/</span> valid_y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8833)

       Prediction
Actual   0   1
     0 202   7
     1  21  10
Number of customers of interest in validaton set 31
Number of customers of interest in 20% top-ranked 17
Ratio 0.55</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Case 21.6 Segmenting Consumers of Bath Soap_files/figure-html/cell-19-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="random-forest-classifier" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-classifier">Random forest classifier</h3>
<div id="cell-41" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> RandomForestClassifier(random_state<span class="op">=</span><span class="dv">1</span>, n_estimators<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>model.fit(train_X, train_y)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>model_pred <span class="op">=</span> model.predict_proba(valid_X)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'actual'</span>: valid_y,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'predicted'</span>: model.predict(valid_X),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>classificationSummary(result.actual, result.predicted)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, figsize<span class="op">=</span>[<span class="dv">5</span>, <span class="dv">5</span>])</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>nx <span class="op">=</span> <span class="bu">round</span>(valid_df.shape[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.2</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>ny <span class="op">=</span> <span class="bu">sum</span>(result.actual[<span class="dv">0</span>:nx])</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>ax.plot([nx, nx,<span class="dv">0</span>], [<span class="dv">0</span>, ny, ny])</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in validaton set'</span>, valid_y.<span class="bu">sum</span>())</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in 20% top-ranked'</span>, ny)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ratio </span><span class="sc">{</span>ny <span class="op">/</span> valid_y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8583)

       Prediction
Actual   0   1
     0 201   8
     1  26   5
Number of customers of interest in validaton set 31
Number of customers of interest in 20% top-ranked 18
Ratio 0.58</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Case 21.6 Segmenting Consumers of Bath Soap_files/figure-html/cell-20-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bagging-classifier" class="level3">
<h3 class="anchored" data-anchor-id="bagging-classifier">Bagging classifier</h3>
<div id="cell-43" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> BaggingClassifier(random_state<span class="op">=</span><span class="dv">1</span>, n_estimators<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>model.fit(train_X, train_y)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>model_pred <span class="op">=</span> model.predict_proba(valid_X)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'actual'</span>: valid_y,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> model_pred],</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'predicted'</span>: model.predict(valid_X),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>classificationSummary(result.actual, result.predicted)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, figsize<span class="op">=</span>[<span class="dv">5</span>, <span class="dv">5</span>])</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>nx <span class="op">=</span> <span class="bu">round</span>(valid_df.shape[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.2</span>)</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>ny <span class="op">=</span> <span class="bu">sum</span>(result.actual[<span class="dv">0</span>:nx])</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>ax.plot([nx, nx,<span class="dv">0</span>], [<span class="dv">0</span>, ny, ny])</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in validaton set'</span>, valid_y.<span class="bu">sum</span>())</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of customers of interest in 20% top-ranked'</span>, ny)</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ratio </span><span class="sc">{</span>ny <span class="op">/</span> valid_y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8542)

       Prediction
Actual   0   1
     0 198  11
     1  24   7
Number of customers of interest in validaton set 31
Number of customers of interest in 20% top-ranked 19
Ratio 0.61</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Case 21.6 Segmenting Consumers of Bath Soap_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>The analysis of the varies models favors the boosting model. It has both the highest accuracy and the gains chart shows that more records are correctly assigned for 20% of the ranked validation set.</p>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s next?</h2>
<p>Many data mining algorithms are iterative in an mathematical sense - iteration is used to find a good, if not best, solution. The modeling process itself is also iterative. In initial exploration, we do not seek the perfect model, merely something to get started. Results are assessed, and we typically continue with a modified approach.</p>
<p>Several steps can be explored next to improve predictive performance:</p>
<ol type="1">
<li>Some of the demographic categorical variables may not have much value being treated as is, as ordered categorical variables. They could be reviewed and turned into binary dummies.</li>
<li>Instead of using a two-cluster model, a multi-cluster model could be used in hopes of deriving more distinguishable clusters. The non-success clusters could then be consolidated. For example, cluster #2 in the 4-cluster model is similar to our cluster 1 (“success”) in the 2-cluster model, only more sharply defined.</li>
<li>Demographic predictors could be added to the original clustering process.</li>
<li>The clustering process, which includes a randomization component that yields variability in resulting clusters, can be repeated, to ensure that the cluster labels reflect some degree of stability. Repetition should show some clustering results that are consistent across various runs. Choosing for your labels a clustering result that is very inconsistent with the others could mean that you are labeling your market segments according to a chance fluke.</li>
<li>In the real world, going beyond the parameters of this case study, CRISA would probably work with the client to add the client’s own purchase data to the model to improve it over time.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>