<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 10: Logistic Regression (LR) – Chad’s Course Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../../">
<script src="../../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../../index.html">
    <span class="navbar-title">Chad’s Course Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ge2021-reserach-technology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">GE2021: Reserach Technology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ge2021-reserach-technology">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter3/chapter3.html">
 <span class="dropdown-text">Chapter3 Slide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mgs3001-python-for-business" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MGS3001: Python for Business</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mgs3001-python-for-business">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mgs3701-data-mining" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MGS3701: Data Mining</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mgs3701-data-mining">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Lecture_Note/chapter1/chapter1_note.html">
 <span class="dropdown-text">Chapter1 Lecture Note</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Lecture_Note/chapter2/chapter2_note.qmd">
 <span class="dropdown-text">Chapter2 Lecture Note</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Class_Activity/ProblemSolution_python/Ch-02-ProbSolutions-Overview.html">
 <span class="dropdown-text">Chapter2 Problem and Solution [Python]</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-10.1-financial-condition-of-banks." id="toc-problem-10.1-financial-condition-of-banks." class="nav-link active" data-scroll-target="#problem-10.1-financial-condition-of-banks.">Problem 10.1 Financial Condition of Banks.</a></li>
  <li><a href="#problem-10.2-identifying-good-system-administrators." id="toc-problem-10.2-identifying-good-system-administrators." class="nav-link" data-scroll-target="#problem-10.2-identifying-good-system-administrators.">Problem 10.2 Identifying Good System Administrators.</a></li>
  <li><a href="#problem-10.3-sales-of-riding-mowers." id="toc-problem-10.3-sales-of-riding-mowers." class="nav-link" data-scroll-target="#problem-10.3-sales-of-riding-mowers.">Problem 10.3 Sales of Riding Mowers.</a></li>
  <li><a href="#problem-10.4-competitive-auctions-on-ebay.com." id="toc-problem-10.4-competitive-auctions-on-ebay.com." class="nav-link" data-scroll-target="#problem-10.4-competitive-auctions-on-ebay.com.">Problem 10.4 Competitive Auctions on eBay.com.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 10: Logistic Regression (LR)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<ol start="3" type="a">
<li>2019-2020 Galit Shmueli, Peter C. Bruce, Peter Gedeck</li>
</ol>
<p><em>Data Mining for Business Analytics: Concepts, Techniques, and Applications in Python</em> (First Edition) Galit Shmueli, Peter C. Bruce, Peter Gedeck, and Nitin R. Patel. 2019.</p>
<p>Date: 2020-03-09</p>
<p>Python Version: 3.8.2 Jupyter Notebook Version: 5.6.1</p>
<p>Packages: - dmba: 0.0.12 - matplotlib: 3.2.0 - numpy: 1.18.1 - pandas: 1.0.1 - scikit-learn: 0.22.2</p>
<p>The assistance from Mr.&nbsp;Kuber Deokar and Ms.&nbsp;Anuja Kulkarni in preparing these solutions is gratefully acknowledged.</p>
</blockquote>
<div id="cell-3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import required packages for this chapter</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression, LogisticRegressionCV</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pylab <span class="im">as</span> plt</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> classificationSummary</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> AIC_score</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> backward_elimination, forward_selection, stepwise_selection</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Working directory:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We assume that data are kept in the same directory as the notebook. If you keep your </span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data in a different folder, replace the argument of the `Path`</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> Path(<span class="st">'.'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># and then load data using </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.read_csv(DATA / ‘filename.csv’)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="problem-10.1-financial-condition-of-banks." class="level1">
<h1>Problem 10.1 Financial Condition of Banks.</h1>
<p>The file <em>Banks.csv</em> includes data on a sample of 20 banks. The “Financial Condition” column records the judgement of an expert on the financial condition of each bank. This outcome variable takes one of two possible values – <em>weak</em> or <em>strong</em>– according to the financial condition of the bank. The predictors are two ratios used in the financial analysis of banks: TotLns&amp;Lses/Assets is the ratio of total loans and leases to total assets and TotExp/Assets is the ratio of total expenses to total assets. The target is to use the two ratios for classifying the financial condition of a new bank.</p>
<p>Run a logistic regression model (on the entire dataset) that model the status of a bank as a function of the two financial measures provided. Specify the <em>success</em> class as <em>weak</em> (this is similar to creating a dummy that is 1 for financially weak banks and 0 otherwise), and use the default cutoff value of 0.5.</p>
<div id="cell-6" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bank_df <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'banks.csv'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># cheack few records</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>bank_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Obs</th>
<th data-quarto-table-cell-role="th">Financial Condition</th>
<th data-quarto-table-cell-role="th">TotCap/Assets</th>
<th data-quarto-table-cell-role="th">TotExp/Assets</th>
<th data-quarto-table-cell-role="th">TotLns&amp;Lses/Assets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>1</td>
<td>9.7</td>
<td>0.12</td>
<td>0.65</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>1</td>
<td>1.0</td>
<td>0.11</td>
<td>0.62</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>1</td>
<td>6.9</td>
<td>0.09</td>
<td>1.02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>1</td>
<td>5.8</td>
<td>0.10</td>
<td>0.67</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>1</td>
<td>4.3</td>
<td>0.11</td>
<td>0.69</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-7" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pretify the variable names</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>bank_df.columns <span class="op">=</span> [c.replace(<span class="st">' '</span>, <span class="st">'_'</span>) <span class="cf">for</span> c <span class="kw">in</span> bank_df.columns]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>bank_df.columns <span class="op">=</span> [c.replace(<span class="st">'&amp;'</span>, <span class="st">''</span>) <span class="cf">for</span> c <span class="kw">in</span> bank_df.columns]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>bank_df.columns <span class="op">=</span> [c.replace(<span class="st">'/'</span>, <span class="st">'_'</span>) <span class="cf">for</span> c <span class="kw">in</span> bank_df.columns]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># drop unwanted variables</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>bank_df.drop(columns <span class="op">=</span> [<span class="st">'Obs'</span>,<span class="st">'TotCap_Assets'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>bank_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Financial_Condition</th>
<th data-quarto-table-cell-role="th">TotExp_Assets</th>
<th data-quarto-table-cell-role="th">TotLnsLses_Assets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>0.12</td>
<td>0.65</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>0.11</td>
<td>0.62</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>0.09</td>
<td>1.02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>0.10</td>
<td>0.67</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>0.11</td>
<td>0.69</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-8" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a logistic regression (set penalty=l2 and C=1e42 to avoid regularization)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> bank_df[<span class="st">'Financial_Condition'</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> bank_df.drop(columns<span class="op">=</span>[<span class="st">'Financial_Condition'</span>])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)</code></pre>
</div>
</div>
<div id="cell-9" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients and AIC measures</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'intercept '</span>, logit_reg.intercept_[<span class="dv">0</span>])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame({<span class="st">'coeff'</span>: logit_reg.coef_[<span class="dv">0</span>]}, index<span class="op">=</span>X.columns).transpose())</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'AIC'</span>, AIC_score(y, logit_reg.predict(X), df <span class="op">=</span> <span class="bu">len</span>(X.columns) <span class="op">+</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept  -14.720832806179043
       TotExp_Assets  TotLnsLses_Assets
coeff      89.832567           8.371267
AIC 18.705839468305996</code></pre>
</div>
</div>
<p><strong>10.1.a.</strong> Write the estimated equation that associates the financial condition of a bank with its two predictors in three formats:</p>
<p><strong>10.1.a.i.</strong> The logit as a function of the predictors</p>
<p><strong>Answer:</strong></p>
<p>logit = -14.7208 + (89.8326 * TotExp_Assets) + (8.3713 * TotLnsLses_Assets)</p>
<p><strong>10.1.a.ii.</strong> The odds as a function of the predictors</p>
<p><strong>Answer</strong></p>
<p>Odds = e^(logit) = e^(-14.7208 + (89.8326 * TotExp_Assets) + (8.3713 * TotLns&amp;Lses_Assets)</p>
<p><strong>10.1.a.ii.</strong> The probability as a function of the predictors</p>
<p><strong>Answer:</strong></p>
<p>p = (1 + Exp[-(-14.7208 + (89.8326 * TotExp/Assets) + (8.3713 * TotLns&amp;Lses/Assets)])^-1</p>
<p><strong>10.1.b.</strong> Consider a new bank whose total loans and leases/assets ratio = 0.6 and total expenses/assets ratio = 0.11. From your logistic regression model, estimate the following four quantities for this bank (use Python to do all the intermediate calculations; show your final answers to four decimal places): the logit, the odds, the probability of being financially weak, and the classification of the bank (use cutoff = 0.5).</p>
<div id="cell-21" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># new record</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>new_bank <span class="op">=</span> pd.DataFrame(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    [[<span class="fl">0.11</span>, <span class="fl">0.6</span>]],</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="st">'TotExp_Assets'</span>, <span class="st">'TotLns_Lses_Assets'</span>])</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>new_bank</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TotExp_Assets</th>
<th data-quarto-table-cell-role="th">TotLns_Lses_Assets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.11</td>
<td>0.6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-22" class="cell" data-scrolled="true" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate logit, odds and probability of being financially weak</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>logit_new <span class="op">=</span> <span class="op">-</span><span class="fl">14.7210</span> <span class="op">+</span> (<span class="fl">89.8339</span> <span class="op">*</span> new_bank.TotExp_Assets) <span class="op">+</span> (<span class="fl">8.3713</span> <span class="op">*</span> new_bank.TotLns_Lses_Assets)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"logit = "</span>, logit_new)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>odds <span class="op">=</span> math.exp(<span class="op">-</span>logit_new)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"odds = "</span>, odds)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>prob <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>odds)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"prob = "</span>, prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>logit =  0    0.183509
dtype: float64
odds =  0.8323443846047233
prob =  0.5457489369367221</code></pre>
</div>
</div>
<p>Probability that the new bank is 0.5457 and therefore the predicted class for this new bank is 1, or “financially week”.</p>
<p><strong>10.1.c.</strong> The cutoff value of 0.5 is used in conjunction with the probability of being financially weak. Compute the threshold that should be used if we want to make a classification based on the odds of being financially weak, and the threshold for the corresponding logit.</p>
<p><strong>Answer:</strong></p>
<p>Cutoff value of p=0.5.</p>
<p>Odds = (p) / (1-p) = (0.5) / (1-0.5) = 1</p>
<p>If odds &gt; 1 then classify financial status as “weak” (otherwise classify as “strong”).</p>
<p>Logit = ln (odds) = ln (1) = 0</p>
<p>If Logit &gt; 0 then classify financial status as “weak” (otherwise, classify it as “strong”)</p>
<p>Therefore, a cutoff of 0.5 on the probability of being weak is equivalent to a threshold of 1 on the odds of being weak, and to a threshold of 0 on the logit.</p>
<p><strong>10.1.d.</strong> Interpret the estimated coefficient for the total loans &amp; leases to total assets ratio (TotLns&amp;Lses/Assets) in terms of the odds of being financially weak.</p>
<p><strong>Answer:</strong></p>
<p>A positive coefficient in the logit model translates into a coefficient larger than 1 in the odds model. In the logit model, the estimated coefficient for total expenses-to-assets ratio is 8.37. In the odds models, the coefficient is e^8.37 = 4316. This means that an increase of a unit in total loans and leases-to-assets is associated with an increase in the odds of being financially weak by a factor of 4321.</p>
<p><strong>10.1.e.</strong> When a bank that is in poor financial condition is misclassified as financially strong, the misclassification cost is much higher than when a financially strong bank is misclassified as weak. To minimize the expected cost of misclassification, should the cutoff value for classification (which is currently at 0.5) be increased or decreased?</p>
<p><strong>Answer:</strong></p>
<p>In order to minimize the expected cost of misclassification in this case, we need to decrease the cutoff.</p>
</section>
<section id="problem-10.2-identifying-good-system-administrators." class="level1">
<h1>Problem 10.2 Identifying Good System Administrators.</h1>
<p>A management consultant is studying the roles played by experience and training in a system administrator’s ability to complete a set of tasks in a specified amount of time. In particular, she is interested in discriminating between administrators who are able to complete given tasks within a specified time and those who are not. Data are collected on the performance of 75 randomly selected administrators. They are stored in the file <em>SystemAdministrators.csv</em>.</p>
<p>The variable Experience measures months of full-time system administrator experience, while Training measures the number of relevant training credits. The outcome variable Completed is either Yes or No, according to whether or not the administrator completed the tasks.</p>
<div id="cell-34" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data and review some records</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>admin_df <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'SystemAdministrators.csv'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>admin_df.head()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>admin_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Training</th>
<th data-quarto-table-cell-role="th">Completed task</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10.9</td>
<td>4</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>9.9</td>
<td>4</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>10.4</td>
<td>6</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>13.7</td>
<td>6</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>9.4</td>
<td>8</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">70</td>
<td>5.6</td>
<td>4</td>
<td>No</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">71</td>
<td>5.9</td>
<td>8</td>
<td>No</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">72</td>
<td>6.4</td>
<td>6</td>
<td>No</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">73</td>
<td>3.8</td>
<td>4</td>
<td>No</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">74</td>
<td>5.3</td>
<td>4</td>
<td>No</td>
</tr>
</tbody>
</table>

<p>75 rows × 3 columns</p>
</div>
</div>
</div>
<div id="cell-35" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># preetify the variable names</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>admin_df.columns <span class="op">=</span> [c.replace(<span class="st">' '</span>, <span class="st">'_'</span>) <span class="cf">for</span> c <span class="kw">in</span> admin_df.columns]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>admin_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Index(['Experience', 'Training', 'Completed_task'], dtype='object')</code></pre>
</div>
</div>
<div id="cell-36" class="cell" data-scrolled="true" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert values of response variable from Yes/No to 0/1</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>admin_df.loc[admin_df.Completed_task <span class="op">==</span> <span class="st">'Yes'</span>, <span class="st">'Completed_task'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>admin_df.loc[admin_df.Completed_task <span class="op">==</span> <span class="st">'No'</span>, <span class="st">'Completed_task'</span>] <span class="op">=</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>10.2.a.</strong> Create a scatter plot of Experience vs.&nbsp;Training using color or symbol to distinguish programmers who completed the task from those who did not complete it. Which predictor(s) appear(s) potentially useful for classifying task completion?</p>
<p><strong>Answer:</strong></p>
<div id="cell-39" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot Experience vs. Training </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> admin_df.loc[admin_df[<span class="st">'Completed_task'</span>]<span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>ax.scatter(subset.Training, subset.Experience, marker<span class="op">=</span><span class="st">'o'</span>, label<span class="op">=</span><span class="st">'No'</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>subset1 <span class="op">=</span> admin_df.loc[admin_df[<span class="st">'Completed_task'</span>]<span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>ax.scatter(subset1.Training, subset1.Experience, marker<span class="op">=</span><span class="st">'D'</span>, label<span class="op">=</span><span class="st">'Yes'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Training'</span>)  <span class="co"># set x-axis label</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Experience'</span>)  <span class="co"># set y-axis label</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>handles, labels <span class="op">=</span> ax.get_legend_handles_labels()</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ax.legend(handles, labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-10-ProbSolutions-LR_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the scatterplot we can observe that programmers who completed the task tend to have more experience. Training, however, does not play much a role in task completion. Therefore, the predictor Experience appears more useful for classifying task completion.</p>
<p><strong>10.2.b.</strong> Run a logistic regression model withboth predictors using the entire dataset as training data. Among those who completd the task, what is the percentage of programmers incorrectly classified as failing to complete the task?</p>
<div id="cell-42" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a logistic regression (set penalty=l2 and C=1e42 to avoid regularization)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>admin_df.Completed_task <span class="op">=</span> admin_df.Completed_task.astype(<span class="st">'category'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> admin_df[<span class="st">'Completed_task'</span>]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> admin_df.drop(columns<span class="op">=</span>[<span class="st">'Completed_task'</span>])</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>classes <span class="op">=</span> <span class="bu">list</span>(y.cat.categories)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)</code></pre>
</div>
</div>
<div id="cell-43" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted y</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> logit_reg.predict(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-44" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>classificationSummary(y, y_pred, class_names<span class="op">=</span>classes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9067)

       Prediction
Actual  0  1
     0 58  2
     1  5 10</code></pre>
</div>
</div>
<p>Among those who completed the task (15), 5 are misclassified as failing to complete the tast. So the percentage of programmers incorrectly classified as failing to complete task is 5/15 = 33.33%.</p>
<p><strong>10.2.c.</strong> To decrease the percentage in part (b), should the cutoff probability be increased or decreased?</p>
<p><strong>Answer:</strong></p>
<p>lowering the cutoff will lead to a reduced (or equal) classification error rate for truly completed records.</p>
<p><strong>10.2.d.</strong> How much experience must be accumulated by a programmer with 4 years of training before his or her estimated probability of completing the task exceeds 0.5?</p>
<p><strong>Answer:</strong></p>
<p>The cutoff of 0.5 on the probability of task completion is equivalent to a threshold of 0 on the logit. We therefore write the estimated logit equation, equate it to 0 and set Training=4.</p>
<p>let’s say p = 0.6</p>
<p>Logit = ln [(p) / (1-p)] = 0.4055 = -10.9794 + 1.1267<em>Experience + 0.1805</em>Training.</p>
<p>We plug Training = 4 and solve for Experience.</p>
<p>9.464 months experience must be accumulated by a programmer with 4 years of education before his/her estimated probability of completing the task exceeds 50%.</p>
</section>
<section id="problem-10.3-sales-of-riding-mowers." class="level1">
<h1>Problem 10.3 Sales of Riding Mowers.</h1>
<p>A company that manufactures riding mowers wants to identify the best sales prospects for an intensive sales campaign. In particular, the manufacturer is interested in classifying households as prospective owners or nonowners on the basis of Income (in $1000s) and Lot Size (in 1000 ft<sup>2</sup>). The marketing expert looked at a random sample of 24 households, given in the file <em>RidingMowers.csv</em>. Use all the data to fit a logistic regression of ownership on the two predictors.</p>
<div id="cell-53" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data and review few records</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mower_df <span class="op">=</span> pd.read_csv(DATA<span class="op">/</span><span class="st">'RidingMowers.csv'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>mower_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">Lot_Size</th>
<th data-quarto-table-cell-role="th">Ownership</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>60.0</td>
<td>18.4</td>
<td>Owner</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>85.5</td>
<td>16.8</td>
<td>Owner</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>64.8</td>
<td>21.6</td>
<td>Owner</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>61.5</td>
<td>20.8</td>
<td>Owner</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>87.0</td>
<td>23.6</td>
<td>Owner</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>10.3.a.</strong> What percentage of households in the study were owners of a riding mower?</p>
<div id="cell-55" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># count of owners in the data</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mower_df[<span class="st">'Ownership'</span>].value_counts() <span class="op">/</span> <span class="bu">len</span>(mower_df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Owner       0.5
Nonowner    0.5
Name: Ownership, dtype: float64</code></pre>
</div>
</div>
<p>50% of households were owners of riding mowers.</p>
<p><strong>10.3.b.</strong> Create a scatter plot of Income vs.&nbsp;Lot Size using color or symbol to distinguish owners from nonowners. From the scatter plot, which class seems to have a higher average income, owners or nonowners?</p>
<p><strong>Answer:</strong></p>
<div id="cell-59" class="cell" data-scrolled="true" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scater plot of Income vs. Lot Size </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> mower_df.loc[mower_df[<span class="st">'Ownership'</span>]<span class="op">==</span> <span class="st">'Owner'</span>]</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>ax.scatter(subset.Lot_Size, subset.Income, marker<span class="op">=</span><span class="st">'o'</span>, label<span class="op">=</span><span class="st">'Owner'</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>subset1 <span class="op">=</span> mower_df.loc[mower_df[<span class="st">'Ownership'</span>]<span class="op">==</span> <span class="st">'Nonowner'</span>]</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>ax.scatter(subset1.Lot_Size, subset1.Income, marker<span class="op">=</span><span class="st">'D'</span>, label<span class="op">=</span><span class="st">'Nonowner'</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Lot_Size'</span>)  <span class="co"># set x-axis label</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Income'</span>)  <span class="co"># set y-axis label</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>handles, labels <span class="op">=</span> ax.get_legend_handles_labels()</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>ax.legend(handles, labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-10-ProbSolutions-LR_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the scatterplot it appears that “owners” tend to have a higher average income.</p>
<p><strong>10.3.c.</strong> Among nonowners, what is the percentage of households classified correctly?</p>
<div id="cell-62" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a logistic regression (set penalty=l2 and C=1e42 to avoid regularization)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># change values of response variable from Owner/Nonowner to 1/0</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>mower_df[<span class="st">'Ownership'</span>] <span class="op">=</span> [<span class="dv">1</span> <span class="cf">if</span> v <span class="op">==</span> <span class="st">'Owner'</span> <span class="cf">else</span> <span class="dv">0</span> <span class="cf">for</span> v <span class="kw">in</span> mower_df[<span class="st">'Ownership'</span>]]</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># convert response variable to type categorical</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>mower_df.Ownership <span class="op">=</span> mower_df.Ownership.astype(<span class="st">'category'</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> mower_df[<span class="st">'Ownership'</span>]</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> mower_df.drop(columns<span class="op">=</span>[<span class="st">'Ownership'</span>])</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>classes <span class="op">=</span> <span class="bu">list</span>(y.cat.categories)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)</code></pre>
</div>
</div>
<div id="cell-63" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'intercept '</span>, logit_reg.intercept_[<span class="dv">0</span>])</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame({<span class="st">'coeff'</span>: logit_reg.coef_[<span class="dv">0</span>]}, index<span class="op">=</span>X.columns).transpose())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept  -25.870471875170026
         Income  Lot_Size
coeff  0.110611  0.961144</code></pre>
</div>
</div>
<div id="cell-64" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted y</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> logit_reg.predict(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-65" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>classificationSummary(y, y_pred, class_names<span class="op">=</span>classes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8333)

       Prediction
Actual  0  1
     0 10  2
     1  2 10</code></pre>
</div>
</div>
<p>83.33% (10 out of 12) nononwers are classified correctly.</p>
<p><strong>10.3.d.</strong> To increase the percentage of correctly classified nonowners, should the cutoff probability be increased or decreased?</p>
<p><strong>Answer:</strong></p>
<p>From the classification confusion matrix shown in (c) we can see that 10 of the 12 non-owners are correctly classified. If we increase the cutoff (i.e.&nbsp;make it harder to be classified as an owner), we can reduce the number of non-owners misclassified as owners, and improve the classification performance with non-owners. (Of course, this will be at the cost of misclassifying more of the owners as non-owners.)</p>
<p><strong>10.3.e.</strong> What are the odds that a household with a $60K income and a lot size of 20,000 ft<sup>2</sup> is an owner?</p>
<p><strong>Answer:</strong></p>
<div id="cell-72" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># new household</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Income <span class="op">=</span> <span class="dv">60</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>Lot_Size <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>odds <span class="op">=</span> math.exp(<span class="op">-</span><span class="fl">25.870471875168775</span> <span class="op">+</span> <span class="fl">0.110611</span> <span class="op">*</span> Income <span class="op">+</span> <span class="fl">0.961144</span> <span class="op">*</span> Lot_Size)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>0.9891276606350936</code></pre>
</div>
</div>
<p><strong>10.3.f.</strong> What is the classification of a household with a $60K income and a lot size of 20,000 ft<sup>2</sup>? Use cutoff = 0.5.</p>
<div id="cell-74" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logit for new household</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>logit <span class="op">=</span> <span class="op">-</span><span class="fl">25.870471875168775</span> <span class="op">+</span> <span class="fl">0.110611</span> <span class="op">*</span> Income <span class="op">+</span> <span class="fl">0.961144</span> <span class="op">*</span> Lot_Size</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>odds <span class="op">=</span> math.exp(logit)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>prob <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>odds)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>0.5027329415753625</code></pre>
</div>
</div>
<p>Probability that the new household is 0.50 and thus the predicted class for this new household is 0, or “non-owner”.</p>
<p><strong>10.3.g.</strong> What is the minimum income that a household with 16,000 ft2 lot size should have before it is classified as an owner?</p>
<p>The cutoff of 0.5 on the probability of owner is equivalent to a threshold of 0 on the logit. We therefore write the estimated logit equation, equate it to 0 and set Lot_Size=16.</p>
<p>0 = -25.870471875168775 + 0.110611<em>Income + 0.961144</em>Lot_Size.</p>
<p>We plug Lot_Size = 16 and solve for Income.</p>
<div id="cell-78" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>Income <span class="op">=</span> (<span class="fl">25.870471875168775</span> <span class="op">-</span> (<span class="fl">0.961144</span><span class="op">*</span><span class="dv">16</span>)) <span class="op">/</span> <span class="fl">0.110611</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>Income</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>94.85645980208817</code></pre>
</div>
</div>
<p>The minimum income needed for this household to be classified as “owner” is $94.8368K.</p>
</section>
<section id="problem-10.4-competitive-auctions-on-ebay.com." class="level1">
<h1>Problem 10.4 Competitive Auctions on eBay.com.</h1>
<p>The file <em>eBayAuctions.csv</em> contains information on 1972 auctions transacted on eBay.com during May–June 2004. The goal is to use these data to build a model that will distinguish competitive auctions from noncompetitive ones. A competitive auction is defined as an auction with at least two bids placed on the item being auctioned. The data include variables that describe the item (auction category), the seller (his or her eBay rating), and the auction terms that the seller selected (auction duration, opening price, currency, day of week of auction close). In addition, we have the price at which the auction closed. The goal is to predict whether or not an auction of interest will be competitive.</p>
<p><strong>Data preprocessing.</strong> Create dummy variables for the categorical predictors. These include Category (18 categories), Currency (USD, GBP, Euro), EndDay (Monday–Sunday), and Duration (1, 3, 5, 7, or 10 days).</p>
<p><strong>10.4.a.</strong> Create pivot tables for the mean of the binary outcome (Competitive?) as a function of the various categorical variables (use the original variables, not the dummies). Use the information in the tables to reduce the number of dummies that will be used in the model. For example, categories that appear most similar with respect to the distribution of competitive auctions could be combined.</p>
<p><strong>Answer:</strong></p>
<div id="cell-83" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>ebay_df <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'eBayAuctions.csv'</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>ebay_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>Index(['Category', 'currency', 'sellerRating', 'Duration', 'endDay',
       'ClosePrice', 'OpenPrice', 'Competitive?'],
      dtype='object')</code></pre>
</div>
</div>
<div id="cell-84" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prettify variable names</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>ebay_df.columns <span class="op">=</span> [c.replace(<span class="st">'?'</span>, <span class="st">''</span>) <span class="cf">for</span> c <span class="kw">in</span> ebay_df.columns]</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>ebay_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>Index(['Category', 'currency', 'sellerRating', 'Duration', 'endDay',
       'ClosePrice', 'OpenPrice', 'Competitive'],
      dtype='object')</code></pre>
</div>
</div>
<div id="cell-85" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the variable types</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>ebay_df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>Category         object
currency         object
sellerRating      int64
Duration          int64
endDay           object
ClosePrice      float64
OpenPrice       float64
Competitive       int64
dtype: object</code></pre>
</div>
</div>
<div id="cell-86" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot table of Competitive and Category</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>pivot1 <span class="op">=</span> pd.pivot_table(ebay_df, index<span class="op">=</span> <span class="st">'Category'</span>, values<span class="op">=</span> <span class="st">"Competitive"</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>               aggfunc<span class="op">=</span> [np.mean])</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>pivot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Competitive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">Category</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Antique/Art/Craft</td>
<td>0.564972</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Automotive</td>
<td>0.353933</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Books</td>
<td>0.500000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Business/Industrial</td>
<td>0.666667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Clothing/Accessories</td>
<td>0.504202</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Coins/Stamps</td>
<td>0.297297</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Collectibles</td>
<td>0.577406</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Computer</td>
<td>0.666667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Electronics</td>
<td>0.800000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">EverythingElse</td>
<td>0.235294</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Health/Beauty</td>
<td>0.171875</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Home/Garden</td>
<td>0.656863</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Jewelry</td>
<td>0.365854</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Music/Movie/Game</td>
<td>0.602978</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Photography</td>
<td>0.846154</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pottery/Glass</td>
<td>0.350000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">SportingGoods</td>
<td>0.725806</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Toys/Hobbies</td>
<td>0.529915</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-87" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot table of Competitive and </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>pivot2 <span class="op">=</span> pd.pivot_table(ebay_df, index<span class="op">=</span> <span class="st">'currency'</span>, values<span class="op">=</span> <span class="st">"Competitive"</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>               aggfunc<span class="op">=</span> [np.mean])</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>pivot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Competitive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">currency</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">EUR</td>
<td>0.551595</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">GBP</td>
<td>0.687075</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">US</td>
<td>0.519350</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-88" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot table of Competitive and Category</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>pivot3 <span class="op">=</span> pd.pivot_table(ebay_df, index<span class="op">=</span> <span class="st">'endDay'</span>, values<span class="op">=</span> <span class="st">"Competitive"</span>,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>               aggfunc<span class="op">=</span> [np.mean])</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>pivot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Competitive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">endDay</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Fri</td>
<td>0.466899</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Mon</td>
<td>0.673358</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sat</td>
<td>0.427350</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Sun</td>
<td>0.485207</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Thu</td>
<td>0.603960</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Tue</td>
<td>0.532164</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Wed</td>
<td>0.480000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The categories “Business/Industrials” and “Computers” have same average of the binary variable “Competitive.” This means that the percentage of competitive auctions in each of these two categories is equal. Hence we can combine the two categories into a single category called “Computers.” Similarly, the average of “competitive” for the categories “Antique/Art/Craft” and “Collectibles” are almost same. Therefore, we can combine them into a single category called “collectibles”. The auction ending days “Sunday” and “Friday” have approximately equal averages for “competitive”. So we can combine them into a single category called “Sun_Fri”.</p>
<div id="cell-90" class="cell" data-scrolled="true" data-execution_count="32">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ebay_df.loc[ebay_df.endDay <span class="op">==</span> <span class="st">'Sun'</span>, <span class="st">'endDay'</span>] <span class="op">=</span> <span class="st">'Sun_Fri'</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>ebay_df.loc[ebay_df.endDay <span class="op">==</span> <span class="st">'Fri'</span>, <span class="st">'endDay'</span>] <span class="op">=</span> <span class="st">'Sun_Fri'</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>ebay_df.loc[ebay_df.Category <span class="op">==</span> <span class="st">"Business/Industrial"</span>, <span class="st">'Category'</span>] <span class="op">=</span> <span class="st">'Computer'</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>ebay_df.loc[ebay_df.Category <span class="op">==</span> <span class="st">"Antique/Art/Craft"</span>, <span class="st">'Category'</span>] <span class="op">=</span> <span class="st">'Collectibles'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-91" class="cell" data-scrolled="false" data-execution_count="33">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot table of Competitive and Category</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>pivot1 <span class="op">=</span> pd.pivot_table(ebay_df, index<span class="op">=</span> <span class="st">'Category'</span>, values<span class="op">=</span> <span class="st">"Competitive"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>               aggfunc<span class="op">=</span> [np.mean])</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>pivot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Competitive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">Category</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Automotive</td>
<td>0.353933</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Books</td>
<td>0.500000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Clothing/Accessories</td>
<td>0.504202</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Coins/Stamps</td>
<td>0.297297</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Collectibles</td>
<td>0.572115</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Computer</td>
<td>0.666667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Electronics</td>
<td>0.800000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">EverythingElse</td>
<td>0.235294</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Health/Beauty</td>
<td>0.171875</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Home/Garden</td>
<td>0.656863</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Jewelry</td>
<td>0.365854</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Music/Movie/Game</td>
<td>0.602978</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Photography</td>
<td>0.846154</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pottery/Glass</td>
<td>0.350000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">SportingGoods</td>
<td>0.725806</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Toys/Hobbies</td>
<td>0.529915</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-92" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot table of Competitive and Category</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pivot3 <span class="op">=</span> pd.pivot_table(ebay_df, index<span class="op">=</span> <span class="st">'endDay'</span>, values<span class="op">=</span> <span class="st">"Competitive"</span>,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>               aggfunc<span class="op">=</span> [np.mean])</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>pivot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Competitive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">endDay</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Mon</td>
<td>0.673358</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Sat</td>
<td>0.427350</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sun_Fri</td>
<td>0.476800</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Thu</td>
<td>0.603960</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Tue</td>
<td>0.532164</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Wed</td>
<td>0.480000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>10.4.b.</strong> Split the data into training (60%) and validation (40%) datasets. Run a logistic model with all predictors with a cutoff of 0.5.</p>
<p><strong>Answer:</strong></p>
<p>Split the data into training (60%) and validation (40%) datasets. Use the random seed 202.</p>
<div id="cell-96" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change variable types to appropriate ones</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>ebay_df[<span class="st">'Category'</span>] <span class="op">=</span> ebay_df[<span class="st">'Category'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>ebay_df[<span class="st">'currency'</span>] <span class="op">=</span> ebay_df[<span class="st">'currency'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>ebay_df[<span class="st">'endDay'</span>] <span class="op">=</span> ebay_df[<span class="st">'endDay'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="co"># convert categorical variables into indicator and drop the first column of each of them</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>ebay_df <span class="op">=</span> pd.get_dummies(ebay_df, prefix_sep<span class="op">=</span><span class="st">'_'</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>ebay_df.drop(columns<span class="op">=</span>[<span class="st">'Category_Automotive'</span>, <span class="st">'currency_EUR'</span>, <span class="st">'endDay_Mon'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-97" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predictor and response variables</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>ebay_df[<span class="st">'Competitive'</span>] <span class="op">=</span> ebay_df[<span class="st">'Competitive'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>outcome <span class="op">=</span> <span class="st">'Competitive'</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>predictors <span class="op">=</span> <span class="bu">list</span>(ebay_df.columns)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>predictors.remove(outcome)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> ebay_df[outcome]</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> ebay_df[predictors]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-98" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># split the data into training and validation sets</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>X_train, X_valid, y_train, y_valid <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.40</span>, random_state<span class="op">=</span><span class="dv">202</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-99" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a logistic regression (set penalty=l2 and C=1e42 to avoid regularization)</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>classes <span class="op">=</span> <span class="bu">list</span>(y.cat.categories)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)</code></pre>
</div>
</div>
<div id="cell-100" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'intercept '</span>, logit_reg.intercept_[<span class="dv">0</span>])</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame({<span class="st">'coeff'</span>: logit_reg.coef_[<span class="dv">0</span>]}, index<span class="op">=</span>X.columns).transpose())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept  -0.16233820301376703
       sellerRating  Duration  ClosePrice  OpenPrice  Category_Books  \
coeff     -0.000037 -0.009712    0.084273  -0.098255       -0.030295   

       Category_Clothing/Accessories  Category_Coins/Stamps  \
coeff                      -0.525984              -0.962637   

       Category_Collectibles  Category_Computer  Category_Electronics  ...  \
coeff                0.43238           0.501414              1.162978  ...   

       Category_Pottery/Glass  Category_SportingGoods  Category_Toys/Hobbies  \
coeff                -0.17042                0.485073               0.706662   

       currency_GBP  currency_US  endDay_Sat  endDay_Sun_Fri  endDay_Thu  \
coeff      1.174816     0.305728    -1.05426       -0.711331   -0.724128   

       endDay_Tue  endDay_Wed  
coeff   -0.724097   -0.838984  

[1 rows x 26 columns]</code></pre>
</div>
</div>
<div id="cell-101" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted y for validation set</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>val_pred <span class="op">=</span> logit_reg.predict(X_valid)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>classificationSummary(y_valid, val_pred, class_names<span class="op">=</span>classes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.7592)

       Prediction
Actual   0   1
     0 289  74
     1 116 310</code></pre>
</div>
</div>
<p><strong>10.4.c.</strong> If we want to predict at the start of an auction whether it will be competitive, we cannot use the information on the closing price. Run a logistic model with all predictors as above, excluding price. How does this model compare to the full model with respect to predictive accuracy?</p>
<p><strong>Answer:</strong></p>
<div id="cell-104" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop the predictor 'ClosePrice'</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> X_train.drop(columns<span class="op">=</span>[<span class="st">'ClosePrice'</span>])</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>X_valid <span class="op">=</span> X_valid.drop(columns<span class="op">=</span>[<span class="st">'ClosePrice'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-105" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a logistic regression (set penalty=l2 and C=1e42 to avoid regularization)</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)</code></pre>
</div>
</div>
<div id="cell-106" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'intercept '</span>, logit_reg.intercept_[<span class="dv">0</span>])</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame({<span class="st">'coeff'</span>: logit_reg.coef_[<span class="dv">0</span>]}, index<span class="op">=</span>X_train.columns).transpose())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept  1.239216727766818
       sellerRating  Duration  OpenPrice  Category_Books  \
coeff      -0.00004 -0.080785  -0.007146       -0.220607   

       Category_Clothing/Accessories  Category_Coins/Stamps  \
coeff                       0.285479              -0.815631   

       Category_Collectibles  Category_Computer  Category_Electronics  \
coeff               0.442175            0.98236              1.540873   

       Category_EverythingElse  ...  Category_Pottery/Glass  \
coeff                -1.887026  ...               -0.332043   

       Category_SportingGoods  Category_Toys/Hobbies  currency_GBP  \
coeff                1.358508               0.648472      0.958213   

       currency_US  endDay_Sat  endDay_Sun_Fri  endDay_Thu  endDay_Tue  \
coeff    -0.095301   -1.239433       -0.954428   -1.012888   -0.740699   

       endDay_Wed  
coeff    -0.91522  

[1 rows x 25 columns]</code></pre>
</div>
</div>
<div id="cell-107" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted y for validation set</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>val_pred <span class="op">=</span> logit_reg.predict(X_valid)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>classificationSummary(y_valid, val_pred, class_names<span class="op">=</span>classes)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep track of results</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>accuracies <span class="op">=</span> {}</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>accuracies[<span class="st">'full model'</span>] <span class="op">=</span> [accuracy_score(y_train, logit_reg.predict(X_train)), accuracy_score(y_valid, val_pred)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.6312)

       Prediction
Actual   0   1
     0 213 150
     1 141 285</code></pre>
</div>
</div>
<p>The overall error rate for the full model (1-0.7605 = 23.95%) is much lower than that for the model excluding “close price” (36.63%). Hence the model excluding “close price” has lower predictive accuracy compared to the full model.</p>
<p><strong>10.4.d.</strong> Interpret the meaning of the coefficient for closing price. Does closing price have a practical significance? Is it statistically significant for predicting competitiveness of auctions? (Use a 10% significance level.)</p>
<p><strong>Answer:</strong></p>
<p>The coefficient for “close price” is 0.084431. This positive coefficient means that higher closing prices are associated with a higher probability of the auction being competitive.</p>
<div id="cell-112" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># odds coefficient for close price</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>math.exp(<span class="fl">0.084431</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>1.088097762896088</code></pre>
</div>
</div>
<p>Looking at the odds coefficient (1.1), we see that every $1 increase in the closing price increases the odds of the auction being competitive by a factor of 1.1. We will not use ClosePrice in the remaining questions since closing price won’t be available at the time making predictions.</p>
<p><strong>10.4.e.</strong> Use stepwise regression as described in chapter 6.4 to find the model with the best fit to the training data (highest accuracy). Which predictors are used?</p>
<div id="cell-115" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_model(variables):</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(variables) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>    model.fit(X_train[<span class="bu">list</span>(variables)], y_train)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_model(model, variables):</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(variables) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="dv">0</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> model.predict(X_train[<span class="bu">list</span>(variables)])</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># we negate as score is optimized to be as low as possible</span></span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>accuracy_score(y_train, y_pred)</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a>allVariables <span class="op">=</span> X_train.columns</span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a>best_fitting, var_fitting <span class="op">=</span> stepwise_selection(allVariables, train_model, </span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>                                score_model, verbose<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(var_fitting))</span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> best_fitting.predict(X_valid[<span class="bu">list</span>(var_fitting)])</span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a>classificationSummary(y_valid, y_pred, class_names<span class="op">=</span>classes)</span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-26"><a href="#cb69-26" aria-hidden="true" tabindex="-1"></a>accuracies[<span class="st">'best fitting'</span>] <span class="op">=</span> [accuracy_score(y_train, best_fitting.predict(X_train[<span class="bu">list</span>(var_fitting)])), </span>
<span id="cb69-27"><a href="#cb69-27" aria-hidden="true" tabindex="-1"></a>                              accuracy_score(y_valid, y_pred)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variables: sellerRating, Duration, OpenPrice, Category_Books, Category_Clothing/Accessories, Category_Coins/Stamps, Category_Collectibles, Category_Computer, Category_Electronics, Category_EverythingElse, Category_Health/Beauty, Category_Home/Garden, Category_Jewelry, Category_Music/Movie/Game, Category_Photography, Category_Pottery/Glass, Category_SportingGoods, Category_Toys/Hobbies, currency_GBP, currency_US, endDay_Sat, endDay_Sun_Fri, endDay_Thu, endDay_Tue, endDay_Wed
Start: score=0.00, constant
Step: score=-0.57, add endDay_Sat
Step: score=-0.60, add endDay_Sun_Fri
Step: score=-0.61, add Category_Electronics
Step: score=-0.62, add Category_Toys/Hobbies
Step: score=-0.63, add Category_Jewelry
Step: score=-0.63, add Category_Computer
Step: score=-0.64, add Category_Health/Beauty
Step: score=-0.67, add OpenPrice
Step: score=-0.67, add endDay_Tue
Step: score=-0.67, add sellerRating
Step: score=-0.67, unchanged None
['Category_Computer', 'Category_Electronics', 'Category_Health/Beauty', 'Category_Jewelry', 'Category_Toys/Hobbies', 'OpenPrice', 'endDay_Sat', 'endDay_Sun_Fri', 'endDay_Tue', 'sellerRating']
Confusion Matrix (Accuracy 0.6274)

       Prediction
Actual   0   1
     0 196 167
     1 127 299</code></pre>
</div>
</div>
<p><strong>10.4.f.</strong> Use stepwise regression to find the model with the highest accuracy on the validation data. Which predictors are used?</p>
<p><strong>Answer:</strong></p>
<div id="cell-118" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_model(model, variables):</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(variables) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="dv">0</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> model.predict(X_valid[<span class="bu">list</span>(variables)])</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># we negate as score is optimized to be as low as possible</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>accuracy_score(y_valid, y_pred)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>allVariables <span class="op">=</span> X_train.columns</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>best_predictive, var_predictive <span class="op">=</span> stepwise_selection(allVariables, train_model, </span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>                                score_model, verbose<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(var_predictive))</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> best_predictive.predict(X_valid[<span class="bu">list</span>(var_predictive)])</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a>classificationSummary(y_valid, y_pred, class_names<span class="op">=</span>classes)</span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a>accuracies[<span class="st">'best predictive'</span>] <span class="op">=</span> [accuracy_score(y_train, best_predictive.predict(X_train[<span class="bu">list</span>(var_predictive)])), </span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a>                                 accuracy_score(y_valid, y_pred)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variables: sellerRating, Duration, OpenPrice, Category_Books, Category_Clothing/Accessories, Category_Coins/Stamps, Category_Collectibles, Category_Computer, Category_Electronics, Category_EverythingElse, Category_Health/Beauty, Category_Home/Garden, Category_Jewelry, Category_Music/Movie/Game, Category_Photography, Category_Pottery/Glass, Category_SportingGoods, Category_Toys/Hobbies, currency_GBP, currency_US, endDay_Sat, endDay_Sun_Fri, endDay_Thu, endDay_Tue, endDay_Wed
Start: score=0.00, constant
Step: score=-0.57, add OpenPrice
Step: score=-0.58, add Category_Music/Movie/Game
Step: score=-0.60, add Category_SportingGoods
Step: score=-0.63, add Category_Electronics
Step: score=-0.64, add sellerRating
Step: score=-0.65, add Category_EverythingElse
Step: score=-0.65, unchanged None
['Category_Electronics', 'Category_EverythingElse', 'Category_Music/Movie/Game', 'Category_SportingGoods', 'OpenPrice', 'sellerRating']
Confusion Matrix (Accuracy 0.6489)

       Prediction
Actual   0   1
     0 163 200
     1  77 349</code></pre>
</div>
</div>
<p><strong>10.4.g.</strong> What is the danger of using the best predictive model that you found?</p>
<p><strong>Answer:</strong></p>
<div id="cell-121" class="cell" data-scrolled="true" data-execution_count="48">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(accuracies, index<span class="op">=</span>[<span class="st">'training'</span>, <span class="st">'validation'</span>]).transpose()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">training</th>
<th data-quarto-table-cell-role="th">validation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">full model</td>
<td>0.655959</td>
<td>0.631179</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">best fitting</td>
<td>0.672866</td>
<td>0.627376</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">best predictive</td>
<td>0.641589</td>
<td>0.648923</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The model that was optimized for performance on the training set (best-fitting) has the highest accuracy. However, it also has the smallest accuracy on the validation set. One way to evaluate the degree of overfitting is to compare the error rates of the training and validation sets. The large difference in training set error and validation error (where training set error is smaller than validation set) indicates that the best-fitting model may be overfit to the training data.</p>
<p>The best-predictive model (optimized for accuracy on the validation set) on the other hand, has a small difference between training and validation accuracy. Here, the accuracy on the validation set is even higher than for the training set. This can be an indication that the model is biased towards the validation set.</p>
<p>To avoid bias towards training or validation set, it is best to use cross validation.</p>
<p><strong>10.4.h.</strong> Explain how and why the best-fitting model and the best predictive models are the same or different.</p>
<p>While finding the best-fitted model means fitting the training data set (using measures like accuracy), the best predictive model is one that has highest prediction accuracy with the validation data.</p>
<p><strong>10.4.i.</strong> Use regularized logistic regression with L1 penalty on the training data. Compare its selected predictors and classification performance to the best-fitting and best predictive models.</p>
<div id="cell-126" class="cell" data-scrolled="true" data-execution_count="49">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>logit_reg_L1 <span class="op">=</span> LogisticRegressionCV(cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>, Cs<span class="op">=</span><span class="dv">20</span>, max_iter<span class="op">=</span><span class="dv">500</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>logit_reg_L1.fit(X_train, y_train)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>classificationSummary(logit_reg_L1.predict(X_valid), val_pred, class_names<span class="op">=</span>classes)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>accuracies[<span class="st">'regularized'</span>] <span class="op">=</span> [accuracy_score(y_train, logit_reg_L1.predict(X_train)), </span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>                             accuracy_score(y_valid, logit_reg_L1.predict(X_valid))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8834)

       Prediction
Actual   0   1
     0 289  27
     1  65 408</code></pre>
</div>
</div>
<div id="cell-127" class="cell" data-scrolled="true" data-execution_count="50">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(accuracies, index<span class="op">=</span>[<span class="st">'training'</span>, <span class="st">'validation'</span>]).transpose()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">training</th>
<th data-quarto-table-cell-role="th">validation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">full model</td>
<td>0.655959</td>
<td>0.631179</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">best fitting</td>
<td>0.672866</td>
<td>0.627376</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">best predictive</td>
<td>0.641589</td>
<td>0.648923</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">regularized</td>
<td>0.657650</td>
<td>0.648923</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Regularization leads to a model that has good accuracy on both the training and validation set.</p>
<div id="cell-129" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>cv_result <span class="op">=</span> pd.DataFrame({</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Cs'</span>: logit_reg_L1.Cs_,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'cv_score'</span>: np.mean(logit_reg_L1.scores_[<span class="dv">1</span>], axis<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>cv_result.plot.line(x<span class="op">=</span><span class="st">'Cs'</span>, y<span class="op">=</span><span class="st">'cv_score'</span>, logx<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-10-ProbSolutions-LR_files/figure-html/cell-52-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-130" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print coefficients</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'intercept '</span>, logit_reg.intercept_[<span class="dv">0</span>])</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>coefficients <span class="op">=</span> pd.DataFrame({</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'unregularized'</span>: logit_reg.coef_[<span class="dv">0</span>], </span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'best_fitting'</span>: <span class="dv">0</span>,</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'best_predictive'</span>: <span class="dv">0</span>,</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'L1 regularized'</span>: logit_reg_L1.coef_[<span class="dv">0</span>],</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>    }, index<span class="op">=</span>X_train.columns)</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>coefficients.loc[var_fitting, <span class="st">'best_fitting'</span>] <span class="op">=</span> best_fitting.coef_.ravel()</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>coefficients.loc[var_predictive, <span class="st">'best_predictive'</span>] <span class="op">=</span> best_predictive.coef_.ravel()</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept  1.239216727766818</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="52">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">unregularized</th>
<th data-quarto-table-cell-role="th">best_fitting</th>
<th data-quarto-table-cell-role="th">best_predictive</th>
<th data-quarto-table-cell-role="th">L1 regularized</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">sellerRating</td>
<td>-0.000040</td>
<td>-0.000012</td>
<td>-0.000020</td>
<td>-0.000036</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Duration</td>
<td>-0.080785</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.085876</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">OpenPrice</td>
<td>-0.007146</td>
<td>-0.009041</td>
<td>-0.009020</td>
<td>-0.007419</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Books</td>
<td>-0.220607</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.437808</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Clothing/Accessories</td>
<td>0.285479</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.038999</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Coins/Stamps</td>
<td>-0.815631</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.450466</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Collectibles</td>
<td>0.442175</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.442809</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Computer</td>
<td>0.982360</td>
<td>0.639226</td>
<td>0.000000</td>
<td>0.567203</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Electronics</td>
<td>1.540873</td>
<td>1.128596</td>
<td>1.039034</td>
<td>1.125243</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_EverythingElse</td>
<td>-1.887026</td>
<td>0.000000</td>
<td>-0.479445</td>
<td>-0.455946</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Health/Beauty</td>
<td>-1.728272</td>
<td>-2.077200</td>
<td>0.000000</td>
<td>-1.426092</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Home/Garden</td>
<td>0.619485</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.464107</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Jewelry</td>
<td>-0.301259</td>
<td>-0.817193</td>
<td>0.000000</td>
<td>-0.649345</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Music/Movie/Game</td>
<td>0.503799</td>
<td>0.000000</td>
<td>0.586934</td>
<td>0.386435</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_Photography</td>
<td>1.282746</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.236325</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Pottery/Glass</td>
<td>-0.332043</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.168076</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Category_SportingGoods</td>
<td>1.358508</td>
<td>0.000000</td>
<td>1.173969</td>
<td>1.271161</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Category_Toys/Hobbies</td>
<td>0.648472</td>
<td>0.143210</td>
<td>0.000000</td>
<td>0.608254</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">currency_GBP</td>
<td>0.958213</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.244927</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">currency_US</td>
<td>-0.095301</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.048313</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">endDay_Sat</td>
<td>-1.239433</td>
<td>-1.033639</td>
<td>0.000000</td>
<td>-1.201499</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">endDay_Sun_Fri</td>
<td>-0.954428</td>
<td>-0.749508</td>
<td>0.000000</td>
<td>-0.791568</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">endDay_Thu</td>
<td>-1.012888</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.186941</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">endDay_Tue</td>
<td>-0.740699</td>
<td>-0.599479</td>
<td>0.000000</td>
<td>-0.445839</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">endDay_Wed</td>
<td>-0.915220</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-0.470326</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>In general, we can see that for cases where both the best_fitting and the best_predictive model exclude a predictor, the coefficient in the regularized model is also closer to zero compared to the unregularized model.</p>
<p><strong>10.4.j.</strong> If the major objective is accurate classification, what cutoff value should be used?</p>
<div id="cell-133" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine accuracy for different cutoff values between 0 and 1</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> []</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cutoff <span class="kw">in</span> [v <span class="op">/</span> <span class="dv">1000</span> <span class="cf">for</span> v <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1001</span>)]:</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>    data.append({<span class="st">'cutoff'</span>: cutoff, </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'accuracy'</span>: accuracy_score(y_valid, logit_reg_L1.predict_proba(X_valid)[:, <span class="dv">1</span>] <span class="op">&gt;</span> cutoff)})</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.DataFrame(data)</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> data.plot.line(x<span class="op">=</span><span class="st">'cutoff'</span>, y<span class="op">=</span><span class="st">'accuracy'</span>)</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>ax.axvline(x<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>data.iloc[data[<span class="st">'accuracy'</span>].argmax() <span class="op">-</span> <span class="dv">1</span>:data[<span class="st">'accuracy'</span>].argmax() <span class="op">+</span> <span class="dv">2</span>, :]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">cutoff</th>
<th data-quarto-table-cell-role="th">accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">505</td>
<td>0.505</td>
<td>0.651458</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">506</td>
<td>0.506</td>
<td>0.655260</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">507</td>
<td>0.507</td>
<td>0.653992</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-10-ProbSolutions-LR_files/figure-html/cell-54-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The highest accuracy is achieved with the default cutoff close to 0.5</p>
<p><strong>10.4.k.</strong> Based on these data, what auction settings set by the seller (duration, opening price, ending day, currency) would you recommend as being most likely to lead to a competitive auction?</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>