<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 5: Evaluating Predictive Performance – Chad’s Course Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../../">
<script src="../../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../../index.html">
    <span class="navbar-title">Chad’s Course Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ge2021-reserach-technology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">GE2021: Reserach Technology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ge2021-reserach-technology">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter3/chapter3.html">
 <span class="dropdown-text">Chapter3 Slide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mgs3001-python-for-business" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MGS3001: Python for Business</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mgs3001-python-for-business">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3001/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mgs3701-data-mining" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MGS3701: Data Mining</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mgs3701-data-mining">    
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter1/chapter1.html">
 <span class="dropdown-text">Chapter1 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Lecture_Note/chapter1/chapter1_note.html">
 <span class="dropdown-text">Chapter1 Lecture Note</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/PPT/chapter2/chapter2.html">
 <span class="dropdown-text">Chapter2 Slide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Lecture_Note/chapter2/chapter2_note.html">
 <span class="dropdown-text">Chapter2 Lecture Note</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../../../Course/MGS3701/03_Lecture_Note/LectureNote_Chad/Class_Activity/ProblemSolution_python/Ch-02-ProbSolutions-Overview.html">
 <span class="dropdown-text">Chapter2 Problem and Solution [Python]</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section">5.1</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">5.2</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">5.3</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">5.4</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4">5.6</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5">5.7</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 5: Evaluating Predictive Performance</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<ol start="3" type="a">
<li>2019-2020 Galit Shmueli, Peter C. Bruce, Peter Gedeck</li>
</ol>
<p><em>Data Mining for Business Analytics: Concepts, Techniques, and Applications in Python</em> (First Edition) Galit Shmueli, Peter C. Bruce, Peter Gedeck, and Nitin R. Patel. 2019.</p>
<p>Date: 2020-03-08</p>
<p>Python Version: 3.8.2 Jupyter Notebook Version: 5.6.1</p>
<p>Packages: - dmba: 0.0.12 - matplotlib: 3.2.0 - pandas: 1.0.1 - scikit-learn: 0.22.2</p>
<p>The assistance from Mr.&nbsp;Kuber Deokar and Ms.&nbsp;Anuja Kulkarni in preparing these solutions is gratefully acknowledged.</p>
</blockquote>
<div id="cell-3" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:19.805479Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:19.804283Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.909498Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.910195Z&quot;}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import required packages for this chapter</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, roc_curve, auc</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pylab <span class="im">as</span> plt </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> regressionSummary, classificationSummary</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> liftChart, gainsChart</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>no display found. Using non-interactive Agg backend</code></pre>
</div>
</div>
<div id="cell-4" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.915602Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.915049Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.918599Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.918135Z&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Working directory:</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We assume that data are kept in the same directory as the notebook. If you keep your </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data in a different folder, replace the argument of the `Path`</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># and then load data using </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.read_csv(‘filename.csv’)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section" class="level1">
<h1>5.1</h1>
<p>A data mining routine has been applied to a transaction dataset and has classified 88 records as fraudulent (30 correctly so) and 952 as non-fraudulent (920 correctly so). Construct the confusion matrix and calculate the overall error rate.</p>
<p><strong>Answer:</strong></p>
<pre>classification confusion matrix
|----------------------------------------------------------------------------|
|             |                     Predicted Class                          |
|----------------------------------------------------------------------------|
| Actual Class|             C0               |             C1                |
|----------------------------------------------------------------------------|
|      C0     | n0,0 = number of correctly   | n0,1 = number of C0 cases     | 
|             |  classified C0 cases         |  incorrectly classified as C1 | 
|----------------------------------------------------------------------------|
|      C1     | n1,0 = number of C1 cases in-| n1,1 = number of correctly    |
|             |  coreectly classified as C0  |  classified C1 cases          |
|----------------------------------------------------------------------------|

Therefore in our problem the confusion matrix is

classification confusion matrix
|----------------------------------------------------------------------|
|                    |                 Predicted Class                 |
|----------------------------------------------------------------------|
| Actual Class       |         Fraudulant(1)    |   Non-fraudulant (0) |
|----------------------------------------------------------------------|
| Fraudulant (1)     |             30           |        32            | 
|----------------------------------------------------------------------|
| Non-fraudulant (0) |             58           |       920            |
|----------------------------------------------------------------------|

</pre>
<p>formula for overall error rate</p>
<p>overall Error Rate = (n<sub>0,1</sub> + n<sub>1,0)</sub> / n, where n is the total number of records.</p>
<div id="cell-8" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.928099Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.927173Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.930153Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.930794Z&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> (<span class="dv">32</span> <span class="op">+</span> <span class="dv">58</span>) <span class="op">/</span> <span class="dv">1040</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>error_rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>0.08653846153846154</code></pre>
</div>
</div>
<p>So the overall error rate is 8.65%.</p>
</section>
<section id="section-1" class="level1">
<h1>5.2</h1>
<p>Suppose that this routine has an adjustable cutoff (threshold) mechanism by which you can alter the proportion of records classified as fraudulent. Describe how moving the cutoff up or down would affect</p>
<p><strong>5.2.a.</strong> the classification error rate for records that are truly fraudulent</p>
<p><strong>5.2.b.</strong> the classification error rate for records that are truly nonfraudulent</p>
<p><strong>Answer:</strong></p>
<pre>classification confusion matrix
|--------------------------------------------------------|
|                   |          Predicted Class           |
|--------------------------------------------------------|
| Actual Class      | Fraudulant (1) | Non-fraudulant (0)|
|--------------------------------------------------------|
| Fraudulant (1)    |       a        |         b         |
|--------------------------------------------------------|
| Non-fraudulant (0)|       c        |         d         |
|--------------------------------------------------------|
</pre>
<p>The classification error rate for truly fraudulent records (with this 0.5 cutoff) is b/(a+b)</p>
<p>The classification error rate for truly non-fraudulent records (with this 0.5 cutoff) is c/(c+d)</p>
<p>Lowering the cutoff (here, below 0.5) leads to classifying more records, both fraudulent and non-fraudulent, as fraudulent: a and c both increase, b and d decline.</p>
<p><strong>a.</strong> With respect to the classification error rate for truly fraudulent records, the error rate, b/(a+b), decreases as b goes up. As you lower the standard for calling a record fraudulent, you catch more and more of the real frauds.</p>
<p><strong>b.</strong> With respect to the classification error rate for truly non-fraudulent records, the error rate, c/(c+d), increases as c goes up. As you lower the standard for calling a record fraudulent, you mistakenly identify more and more non-frauds as frauds.</p>
<p>Increasing the cutoff (here, above 0.5) leads to classifying more records, both fraudulent and non-fraudulent, as non-fraudulent: b and d both increase, a and c decline.</p>
<p><strong>a.</strong> With respect to the classification error rate for truly fraudulent records, the error rate, b/(a+b), increases as b goes up. As you raise the standard for calling a record fraudulent, you miss more and more of the real frauds.</p>
<p><strong>b.</strong> With respect to the classification error rate for truly non-fraudulent records, the error rate, c/(c+d), decreases as d goes up. As you raise the standard for calling a record fraudulent, fewer non-frauds get mis-labeled as frauds.</p>
</section>
<section id="section-2" class="level1">
<h1>5.3</h1>
<p>FiscalNote is a startup founded by a Washington, DC entrepreneur and funded by a Singapore sovereign wealth fund, the Winklevoss twins of Facebook fame, and others. It uses machine learning and data mining techniques to predict for its clients whether legislation in the US Congress and in US state legislatures will pass or not. The company reports 94% accuracy. (Washington Post, November 21, 2014, “Capital Business”)</p>
<p>Considering just bills introduced in the US Congress, do a bit of internet research to learn about numbers of bills introduced and passage rates. Identify the possible types of misclassifications, and comment on the use of overall accuracy as a metric. Include a discussion of other possible metrics and the potential role of propensities.</p>
<p><strong>Answer:</strong></p>
<p>Web research on govtrack.us shows that, in the 113th Congress (which covered 2013 and 2014), over 10,000 pieces of legislation were introduced but only 3% passed as enacted laws. “Enacted laws” does not include the 6% that were passed as (usually meaningless) resolutions.</p>
<p>If we focus just on classifying each bill, and use overall accuracy as a metric, we could achieve 97% accuracy just by predicting that nothing will pass (as a law).</p>
<p>A data mining model might make two types of classification errors - saying that a bill will pass when it won’t, and saying a bill won’t pass when it will. The second type of error is probably more costly than the first - identifying the small number of bills that will pass is probably of more interest than overall accuracy. Therefore, a useful metric would be sensitivity to “will pass” - the proportion of “will pass” bills that were correctly predicted (alongside with specificity, which is the proportion of “will not pass” that are correctly ruled out).</p>
<p>However, rather than just assigning a 0/1 class to each bill (classification), we will probably be more interested in ranking the bills and estimating a propensity (probability) for passage for each bill. We would then focus on the high probability bills, and not be so concerned with the low probability bills.</p>
<p>With ranking as our goal, we could use lift as a metric for how well a model separates out the “will pass” bills. As part of the calculation for lift, the bills would be ranked by their propensity to pass. Lift gives a picture of how much better the model does than not using a model.</p>
</section>
<section id="section-3" class="level1">
<h1>5.4</h1>
<p>Consider Figure 5.12, the decile lift chart for the transaction data model, applied to new data.</p>
<p><strong>5.4.a.</strong> Interpret the meaning of the first and second bars from the left.</p>
<p><strong>Answer:</strong></p>
<p>Left-most bar: If we take the 10% “most probable 1’s (frauds)” (as ranked by the model), it will catch 6.5 times as many 1’s (frauds), as would a random selection of 10% of the records.</p>
<p>#2nd bar from left: If we take the second highest decile (10%) of records that are ranked by the model as “the most probable 1’s (frauds)” it will catch 2.7 times as many 1’s (frauds), as would a random selection of 10% of the records.</p>
<p><strong>5.4.b.</strong> Explain how you might use this information in practice.</p>
<p><strong>Answer:</strong></p>
<p>Consider a tax authority that wants to allocate their resources for investigating firms that are most likely to submit fraudulent tax returns. Suppose that there are resources for auditing only 10% of firms. Rather than taking a random sample, they can select the top 10% of firms that are predicted to be most likely to report fraudulently (according to the decile chart). Or, to preserve the principle that anyone might be audited, they can establish differential probabilities for being sampled – those in the top deciles being much more likely to be audited.</p>
<p><strong>5.4.c.</strong> Another analyst comments that you could improve the accuracy of the model by classifying everything as nonfraudulent. If you do that, what is the error rate?</p>
<p><strong>Answer:</strong></p>
<p>We have the following confusion matrix from Problem 5.1.</p>
<pre>classification confusion matrix
|----------------------------------------------------------------------|
|                    |                 Predicted Class                 |
|----------------------------------------------------------------------|
| Actual Class       |         Fraudulant(1)    |   Non-fraudulant (0) |
|----------------------------------------------------------------------|
| Fraudulant (1)     |             30           |        32            | 
|----------------------------------------------------------------------|
| Non-fraudulant (0) |             58           |       920            |
|----------------------------------------------------------------------|

</pre>
<p>According to the new analyst our classification confusion matrix becomes-</p>
<pre>classification confusion matrix
|----------------------------------------------------------------------|
|                    |                 Predicted Class                 |
|----------------------------------------------------------------------|
| Actual Class       |         Fraudulant(1)    |   Non-fraudulant (0) |
|----------------------------------------------------------------------|
| Fraudulant (1)     |              0           |        88            | 
|----------------------------------------------------------------------|
| Non-fraudulant (0) |              0           |       952            |
|----------------------------------------------------------------------|

</pre>
<div id="cell-29" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.938273Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.937217Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.940721Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.941444Z&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall misclassification rate</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> <span class="dv">88</span><span class="op">/</span><span class="dv">1040</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>error_rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>0.08461538461538462</code></pre>
</div>
</div>
<p>We see that the misclassification error rate is lower (8.46%) with the “everything non-fraudulent” proposal (although only slightly).</p>
<p><strong>5.4.d.</strong> Comment on the usefulness, in this situation, of these two metrics of model performance (error rate and lift).</p>
<p><strong>Answer:</strong></p>
<p>The likely purpose of this analysis is to identify fraudulent records. The overall “error rate” is not likely to help much in evaluating competing methods for doing so. The key factor here is the ability to identify records that have a high probability of being fraudulent, and this is what lift measures. Using lift, you can “descend” through the records in order of probability of being fraudulent, knowing at each point how much more likely you are to be getting a fraudulent record than naively selecting at random. The “error rate” measure, by contrast, reveals nothing about the efficiency of identifying fraudulent records.</p>
<p>The vast majority of records are non-fraudulent, and correctly classifying nonfraudulent records drives the overall error rate. One can achieve a very respectably low error rate just by classifying everything as non-fraudulent, which is not practically useful.</p>
<p><strong>5.5.</strong></p>
<p>A large number of insurance records are to be examined to develop a model for predicting fraudulent claims. Of the claims in the historical database, 1% were judged to be fraudulent. A sample is taken to develop a model, and oversampling is used to provide a balanced sample in light of the very low response rate. When applied to this sample (n = 800), the model ends up correctly classifying 310 frauds, and 270 nonfrauds. It missed 90 frauds, and classified 130 records incorrectly as frauds when they were not.</p>
<p><strong>5.5.a.</strong> Produce the confusion matrix for the sample as it stands.</p>
<p><strong>Answer:</strong></p>
<pre>classification confusion matrix
|--------------------------------------------------------|
|                   |          Predicted Class           |
|--------------------------------------------------------|
| Actual Class      |        1       |         0         |
|--------------------------------------------------------|
|          1        |      310       |        90         |
|--------------------------------------------------------|
|          0        |      130       |       270         |
|--------------------------------------------------------|
</pre>
<div id="cell-38" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.946700Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.946145Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.950823Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.950332Z&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Misclassification rate</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>miscl_rate1 <span class="op">=</span> (<span class="dv">90</span> <span class="op">+</span> <span class="dv">130</span>) <span class="op">/</span> <span class="dv">800</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>miscl_rate1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>0.275</code></pre>
</div>
</div>
<p>So the overall misclassification rate is 27.5%.</p>
<p>The model ends up classifying (310 + 130) / 800 = 0.55 = 55% of the records as fraudulent.</p>
<p><strong>5.5.b.</strong> Find the adjusted misclassification rate (adjusting for the oversampling).</p>
<p><strong>Answer:</strong></p>
Now we need to add enough zeros so that the 1’s only constitute 1% of the total and the 0’s constitute 99% of the total (where is X is the total).
<pre>                                                                                                           
400 + 0.99*x = x
Therefore x = 40, 000
Number of zeros = 0.99 * 40, 000 = 39600

#classification confusion matrix
|-------------------------------------------------------------|
|                   |          Predicted Class       |        |
|-------------------------------------------------------------|
|    Actual Class   |        1       |         0     | Total  |
|-------------------------------------------------------------|
|          1        |      310       |        90     | 400    |
|----------------------------------------------------|--------|
|          0        |    12870       |     26730     | 39600  |
|----------------------------------------------------|--------|
|       Total       |    13180       |     26820     | 40000  |
|-------------------------------------------------------------|
</pre>
<div id="cell-44" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.955835Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.955242Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.959269Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.959689Z&quot;}" data-scrolled="true" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overall misclassification rate</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>miscl_rate2 <span class="op">=</span> (<span class="dv">90</span> <span class="op">+</span> <span class="dv">12870</span>) <span class="op">/</span> <span class="dv">40000</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>miscl_rate2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>0.324</code></pre>
</div>
</div>
<p>The model ends up classifying (310 + 12870) / 40000 = 0.3295 = 32.95% of the records as fraudulent.</p>
<p><strong>5.5.c.</strong> What percentage of new records would you expect to be classified as fraudulent?</p>
<p>From the above calculations, we expect 32.95% of the records to be classified as frauds.</p>
</section>
<section id="section-4" class="level1">
<h1>5.6</h1>
<p>A firm that sells software services has been piloting a new product and has records of 500 customers who have either bought the services or decided not to. The target value is the estimated profit from each sale (excluding sales costs). The global mean is about 2128 dollars. However, the cost of the sales effort is not cheap— the company figures it comes to 2500 dollars for each of the 500 customers (whether they buy or not). The firm developed a predictive model in hopes of being able to identify the top spenders in the future. The cumulative gains and decile lift charts for the validation set are shown in Figure 5.13.</p>
<p><strong>5.6.a</strong> If the company begins working with a new set of 1000 leads to sell the same services, similar to the 500 in the pilot study, without any use of predictive modeling to target sales efforts, what is the estimated profit?</p>
<p><strong>Answer:</strong></p>
<p>If the 1000 new leads are like those in the pilot, then the company can expect the same mean profit per sale of 2500 dollars, or 2,500,000 dollars for the 1000 leads. This does not include the cost of the sales effort, which would cost an estimated 2.5 million dollars. In other words, it would not be a profitable move.</p>
<p><strong>5.6.b.</strong> If the firm wants the average profit on each sale to roughly double the sales effort cost, and applies an appropriate cutoff with this predictive model to a new set of 1000 leads, how far down the new list of 1000 should it proceed (how many deciles)?</p>
<p><strong>Answer:</strong></p>
<p>If the profit must double the sales effort cost, that would be 5000 dollars. This is twice the average profit across all customers. The company could achieve this by attempting sales to the first (top) decile among the customers, where the lift is about 2.1. However, it should not go beyond this point.</p>
<p><strong>5.6.c</strong> Still considering the new list of 1000 leads, if the company applies this predictive model with a lower cutoff of 2500, how far should it proceed down the ranked leads, in terms of deciles?</p>
<p><strong>Answer:</strong></p>
<p>If the cutoff is lowered to 2500 dollars, a lift as low as 2500/2500 or 1.0 could be tolerated. This would mean going all the way through the 5th decile, or half the customers. It would also mean that the product is breakeven at the margin (i.e.&nbsp;the last group of leads produces no net profit)</p>
<p><strong>5.6.d.</strong> Why use this two-stage process for predicting sales—why not simply develop a model for predicting profit for the 1000 new leads?</p>
<p><strong>Answer:</strong></p>
<p>A model to predict overall profit for all 1000 leads would not be useful. The profit would be zero. Individual profit predictions for each of the 1000 leads would be useful, and might be sufficient, but generating staged solutions (corresponding to different cutoffs and differing lift) helps translate the optimization problem into a business problem, and frame a limited number of decision options for managers. <em>Note: different interpretations of the question are possible with respect to whether profit for all 1000 leads all together is intended, or profit for each of the 1000 leads individually, so some leeway is accorded in marking</em>.</p>
</section>
<section id="section-5" class="level1">
<h1>5.7</h1>
<p>Table 5.7 shows a small set of predictive model validation results for a classification model, with both actual values and propensities.</p>
<p><strong>5.7.a.</strong> Calculate error rates, sensitivity, and specificity using cutoffs of 0.25, 0.5, and 0.75.</p>
<p><strong>Answer:</strong></p>
<div id="cell-64" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.969088Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.968294Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.971874Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.971382Z&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame of data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> {<span class="st">'Propensity'</span>: [<span class="fl">0.03</span>, <span class="fl">0.52</span>, <span class="fl">0.38</span>, <span class="fl">0.82</span>, <span class="fl">0.33</span>, <span class="fl">0.42</span>, <span class="fl">0.55</span>, <span class="fl">0.59</span>, <span class="fl">0.09</span>, <span class="fl">0.21</span>, <span class="fl">0.43</span>, <span class="fl">0.04</span>, <span class="fl">0.08</span>, <span class="fl">0.13</span>, <span class="fl">0.01</span>, <span class="fl">0.79</span>, <span class="fl">0.42</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">0.29</span>, <span class="fl">0.08</span>, <span class="fl">0.02</span>],</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Actual'</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>]}</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to data frame</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-65" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.979072Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.978300Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.989205Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.989848Z&quot;}" data-scrolled="false" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cutoff = 0.25</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>Predicted <span class="op">=</span> [<span class="dv">1</span> <span class="cf">if</span> p <span class="op">&gt;</span> <span class="fl">0.25</span> <span class="cf">else</span> <span class="dv">0</span> <span class="cf">for</span> p <span class="kw">in</span> df.Propensity]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>classificationSummary(df.Actual, Predicted, class_names<span class="op">=</span>[<span class="st">'0'</span>, <span class="st">'1'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.6000)

       Prediction
Actual 0 1
     0 9 8
     1 0 3</code></pre>
</div>
</div>
<div id="cell-66" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:20.995581Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:20.994933Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:20.999091Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:20.998086Z&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overall error rate</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> (<span class="dv">8</span>) <span class="op">/</span> <span class="dv">20</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Error Rate = '</span>, error_rate)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># sensitivity</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> (<span class="dv">3</span>) <span class="op">/</span> (<span class="dv">3</span><span class="op">+</span><span class="dv">0</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Sensitivity='</span>,sensitivity)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># specificity</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>specificity <span class="op">=</span> (<span class="dv">9</span>) <span class="op">/</span> (<span class="dv">8</span><span class="op">+</span><span class="dv">9</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Specificity = '</span>, specificity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error Rate =  0.4

Sensitivity= 1.0

Specificity =  0.5294117647058824</code></pre>
</div>
</div>
<div id="cell-67" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:21.005891Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:21.005227Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:21.009320Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:21.009744Z&quot;}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cutoff = 0.5</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>Predicted <span class="op">=</span> [<span class="dv">1</span> <span class="cf">if</span> p <span class="op">&gt;</span> <span class="fl">0.5</span> <span class="cf">else</span> <span class="dv">0</span> <span class="cf">for</span> p <span class="kw">in</span> df.Propensity]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>classificationSummary(df.Actual, Predicted, class_names<span class="op">=</span>[<span class="st">'0'</span>, <span class="st">'1'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9000)

       Prediction
Actual  0  1
     0 15  2
     1  0  3</code></pre>
</div>
</div>
<div id="cell-68" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:21.015497Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:21.014813Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:21.020768Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:21.019902Z&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overall error rate</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> (<span class="dv">2</span>) <span class="op">/</span> <span class="dv">20</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Error Rate = '</span>, error_rate)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># sensitivity</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> (<span class="dv">3</span>) <span class="op">/</span> (<span class="dv">3</span><span class="op">+</span><span class="dv">0</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Sensitivity='</span>,sensitivity)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># specificity</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>specificity <span class="op">=</span> (<span class="dv">15</span>) <span class="op">/</span> (<span class="dv">2</span><span class="op">+</span><span class="dv">15</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Specificity = '</span>, specificity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error Rate =  0.1

Sensitivity= 1.0

Specificity =  0.8823529411764706</code></pre>
</div>
</div>
<div id="cell-69" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:21.031587Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:21.030506Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:21.037109Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:21.036319Z&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cutoff = 0.75</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>Predicted <span class="op">=</span> [<span class="dv">1</span> <span class="cf">if</span> p <span class="op">&gt;</span> <span class="fl">0.75</span> <span class="cf">else</span> <span class="dv">0</span> <span class="cf">for</span> p <span class="kw">in</span> df.Propensity]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>classificationSummary(df.Actual, Predicted, class_names<span class="op">=</span>[<span class="st">'0'</span>, <span class="st">'1'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9500)

       Prediction
Actual  0  1
     0 17  0
     1  1  2</code></pre>
</div>
</div>
<div id="cell-70" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:21.043401Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:21.042680Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:21.048394Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:21.047569Z&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overall error rate</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> (<span class="dv">1</span>) <span class="op">/</span> <span class="dv">20</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Error Rate = '</span>, error_rate)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># sensitivity</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> (<span class="dv">2</span>) <span class="op">/</span> (<span class="dv">2</span><span class="op">+</span><span class="dv">1</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Sensitivity='</span>,sensitivity)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># specificity</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>specificity <span class="op">=</span> (<span class="dv">17</span>) <span class="op">/</span> (<span class="dv">0</span><span class="op">+</span><span class="dv">17</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Specificity = '</span>, specificity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error Rate =  0.05

Sensitivity= 0.6666666666666666

Specificity =  1.0</code></pre>
</div>
</div>
<p><strong>5.7.b.</strong> Create a decile lift chart.</p>
<p><strong>Answer:</strong></p>
<div id="cell-73" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2020-11-20T16:50:21.055547Z&quot;,&quot;iopub.status.busy&quot;:&quot;2020-11-20T16:50:21.053355Z&quot;,&quot;iopub.status.idle&quot;:&quot;2020-11-20T16:50:21.213333Z&quot;,&quot;shell.execute_reply&quot;:&quot;2020-11-20T16:50:21.212587Z&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># decile lift chart</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sort data by propensities</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.sort_values(by<span class="op">=</span>[<span class="st">'Propensity'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create decile lift chart</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>liftChart(df.Actual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>&lt;AxesSubplot:title={'center':'Decile Lift Chart'}, xlabel='Percentile', ylabel='Lift'&gt;</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>