<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 12: Discriminant Analysis – Chad’s Course Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../../">
<script src="../../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../../index.html">
    <span class="navbar-title">Chad’s Course Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../../Course/GE2021/03_Lecture_Note/LectureNote_Chad/PPT/chapter0/chapter0.html"> 
<span class="menu-text">test</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-12.1-personal-loan-acceptance" id="toc-problem-12.1-personal-loan-acceptance" class="nav-link active" data-scroll-target="#problem-12.1-personal-loan-acceptance">Problem 12.1: Personal Loan Acceptance</a>
  <ul class="collapse">
  <li><a href="#problem-12.1.a" id="toc-problem-12.1.a" class="nav-link" data-scroll-target="#problem-12.1.a">Problem 12.1.a</a></li>
  <li><a href="#problem-12.1.b" id="toc-problem-12.1.b" class="nav-link" data-scroll-target="#problem-12.1.b">Problem 12.1.b</a></li>
  <li><a href="#problem-12.1.b.ii" id="toc-problem-12.1.b.ii" class="nav-link" data-scroll-target="#problem-12.1.b.ii">Problem 12.1.b.ii</a></li>
  <li><a href="#problem-12.1.b.iii" id="toc-problem-12.1.b.iii" class="nav-link" data-scroll-target="#problem-12.1.b.iii">Problem 12.1.b.iii</a></li>
  <li><a href="#problem-12.1.c" id="toc-problem-12.1.c" class="nav-link" data-scroll-target="#problem-12.1.c">Problem 12.1.c</a></li>
  <li><a href="#problem-12.1.d" id="toc-problem-12.1.d" class="nav-link" data-scroll-target="#problem-12.1.d">Problem 12.1.d</a></li>
  <li><a href="#problem-12.1.e" id="toc-problem-12.1.e" class="nav-link" data-scroll-target="#problem-12.1.e">Problem 12.1.e</a></li>
  <li><a href="#problem-12.1.f" id="toc-problem-12.1.f" class="nav-link" data-scroll-target="#problem-12.1.f">Problem 12.1.f</a></li>
  </ul></li>
  <li><a href="#problem-12.2-identifying-good-system-administrators" id="toc-problem-12.2-identifying-good-system-administrators" class="nav-link" data-scroll-target="#problem-12.2-identifying-good-system-administrators">Problem 12.2: Identifying Good System Administrators</a>
  <ul class="collapse">
  <li><a href="#problem-12.2.a" id="toc-problem-12.2.a" class="nav-link" data-scroll-target="#problem-12.2.a">Problem 12.2.a</a></li>
  <li><a href="#problem-12.2.b" id="toc-problem-12.2.b" class="nav-link" data-scroll-target="#problem-12.2.b">Problem 12.2.b</a></li>
  <li><a href="#problem-12.2.c" id="toc-problem-12.2.c" class="nav-link" data-scroll-target="#problem-12.2.c">Problem 12.2.c</a></li>
  <li><a href="#problem-12.2.d" id="toc-problem-12.2.d" class="nav-link" data-scroll-target="#problem-12.2.d">Problem 12.2.d</a></li>
  <li><a href="#problem-12.2.e" id="toc-problem-12.2.e" class="nav-link" data-scroll-target="#problem-12.2.e">Problem 12.2.e</a></li>
  </ul></li>
  <li><a href="#problem-12.3-detecting-spam-e-mail-from-the-uci-machine-learning-repository" id="toc-problem-12.3-detecting-spam-e-mail-from-the-uci-machine-learning-repository" class="nav-link" data-scroll-target="#problem-12.3-detecting-spam-e-mail-from-the-uci-machine-learning-repository">Problem 12.3: Detecting Spam E-mail (from the UCI Machine Learning Repository)</a>
  <ul class="collapse">
  <li><a href="#problem-12.3.a" id="toc-problem-12.3.a" class="nav-link" data-scroll-target="#problem-12.3.a">Problem 12.3.a</a></li>
  <li><a href="#problem-12.3.b" id="toc-problem-12.3.b" class="nav-link" data-scroll-target="#problem-12.3.b">Problem 12.3.b</a></li>
  <li><a href="#problem-12.3.c" id="toc-problem-12.3.c" class="nav-link" data-scroll-target="#problem-12.3.c">Problem 12.3.c</a></li>
  <li><a href="#problem-12.3.d" id="toc-problem-12.3.d" class="nav-link" data-scroll-target="#problem-12.3.d">Problem 12.3.d</a></li>
  <li><a href="#problem-12.3.e" id="toc-problem-12.3.e" class="nav-link" data-scroll-target="#problem-12.3.e">Problem 12.3.e</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 12: Discriminant Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<ol start="3" type="a">
<li>2019-2020 Galit Shmueli, Peter C. Bruce, Peter Gedeck</li>
</ol>
<p><em>Data Mining for Business Analytics: Concepts, Techniques, and Applications in Python</em> (First Edition) Galit Shmueli, Peter C. Bruce, Peter Gedeck, and Nitin R. Patel. 2019.</p>
<p>Date: 2020-03-08</p>
<p>Python Version: 3.8.2 Jupyter Notebook Version: 5.6.1</p>
<p>Packages: - dmba: 0.0.12 - matplotlib: 3.2.0 - numpy: 1.18.1 - pandas: 1.0.1 - scikit-learn: 0.22.2</p>
<p>The assistance from Mr.&nbsp;Kuber Deokar and Ms.&nbsp;Anuja Kulkarni in preparing these solutions is gratefully acknowledged.</p>
</blockquote>
<div id="cell-3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import required packages for this chapter</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.discriminant_analysis <span class="im">import</span> LinearDiscriminantAnalysis</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pylab <span class="im">as</span> plt</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> classificationSummary</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dmba <span class="im">import</span> gainsChart, liftChart</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Working directory:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We assume that data are kept in the same directory as the notebook. If you keep your </span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data in a different folder, replace the argument of the `Path`</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> Path(<span class="st">'.'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># and then load data using </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.read_csv(DATA / ‘filename.csv’)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="problem-12.1-personal-loan-acceptance" class="level1">
<h1>Problem 12.1: Personal Loan Acceptance</h1>
<p>Universal Bank is a relatively young bank growing rapidly in terms of overall customer acquisition. The majority of these customers are liability customers with varying sizes of relationship with the bank. The customer base of asset customers is quite small, and the bank is interested in expanding this base rapidly to bring in more loan business. In particular, it wants to explore ways of converting its liability customers to personal loan customers.</p>
<p>A campaign the bank ran for liability customers last year showed a healthy conversion rate of over 9% successes. This has encouraged the retail marketing department to devise smarter campaigns with better target marketing. The goal of our analysis is to model the previous campaign’s customer behavior to analyze what combination of factors make a customer more likely to accept a personal loan. This will serve as the basis for the design of a new campaign.</p>
<p>The file <em>UniversalBank.csv</em> contains data on 5000 customers. The data include customer demographic information (e.g., age, income), the customer’s relationship with the bank (e.g., mortgage, securities account), and the customer response to the last personal loan campaign (Personal Loan). Among these 5000 customers, only 480 (= 9.6%) accepted the personal loan that was offered to them in the previous campaign.</p>
<p>Partition the data (60% training and 40% validation) and then perform a discriminant analysis that models Personal Loan as a function of the remaining predictors (excluding zip code). Remember to turn categorical predictors with more than two categories into dummy variables first. Specify the success class as 1 (personal loan acceptance), and use the default cutoff value of 0.5.</p>
<div id="cell-6" class="cell" data-scrolled="true" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bank_df <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'UniversalBank.csv'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bank_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">ZIP Code</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">CCAvg</th>
<th data-quarto-table-cell-role="th">Education</th>
<th data-quarto-table-cell-role="th">Mortgage</th>
<th data-quarto-table-cell-role="th">Personal Loan</th>
<th data-quarto-table-cell-role="th">Securities Account</th>
<th data-quarto-table-cell-role="th">CD Account</th>
<th data-quarto-table-cell-role="th">Online</th>
<th data-quarto-table-cell-role="th">CreditCard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>25</td>
<td>1</td>
<td>49</td>
<td>91107</td>
<td>4</td>
<td>1.6</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>45</td>
<td>19</td>
<td>34</td>
<td>90089</td>
<td>3</td>
<td>1.5</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>39</td>
<td>15</td>
<td>11</td>
<td>94720</td>
<td>1</td>
<td>1.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>35</td>
<td>9</td>
<td>100</td>
<td>94112</td>
<td>1</td>
<td>2.7</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>35</td>
<td>8</td>
<td>45</td>
<td>91330</td>
<td>4</td>
<td>1.0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-7" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop ID and zip code columns</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>bank_df <span class="op">=</span> bank_df.drop(columns<span class="op">=</span>[<span class="st">'ID'</span>, <span class="st">'ZIP Code'</span>])</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use one-hot-encoding for Education</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> bank_df.drop(columns<span class="op">=</span>[<span class="st">'Personal Loan'</span>])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.get_dummies(X, columns<span class="op">=</span>[<span class="st">'Education'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> bank_df[<span class="st">'Personal Loan'</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>X.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Mortgage',
       'Securities Account', 'CD Account', 'Online', 'CreditCard',
       'Education_2', 'Education_3'],
      dtype='object')</code></pre>
</div>
</div>
<div id="cell-8" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>train_X, valid_X, train_y, valid_y <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Training set:'</span>, train_X.shape, <span class="st">'Validation set:'</span>, valid_X.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set: (3000, 12) Validation set: (2000, 12)</code></pre>
</div>
</div>
<div id="cell-9" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>da_class <span class="op">=</span> LinearDiscriminantAnalysis()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>da_class.fit(X, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)</code></pre>
</div>
</div>
<section id="problem-12.1.a" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.a">Problem 12.1.a</h2>
<p>Compute summary statistics for the predictors separately for loan acceptors and nonacceptors. For continuous predictors, compute the mean and standard deviation. For categorical predictors, compute the percentages. Are there predictors where the two classes differ substantially?</p>
<div id="cell-11" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bank_df[y<span class="op">==</span><span class="dv">1</span>].describe().loc[[<span class="st">'mean'</span>, <span class="st">'std'</span>],:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">CCAvg</th>
<th data-quarto-table-cell-role="th">Education</th>
<th data-quarto-table-cell-role="th">Mortgage</th>
<th data-quarto-table-cell-role="th">Personal Loan</th>
<th data-quarto-table-cell-role="th">Securities Account</th>
<th data-quarto-table-cell-role="th">CD Account</th>
<th data-quarto-table-cell-role="th">Online</th>
<th data-quarto-table-cell-role="th">CreditCard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>45.066667</td>
<td>19.843750</td>
<td>144.745833</td>
<td>2.612500</td>
<td>3.905354</td>
<td>2.233333</td>
<td>100.845833</td>
<td>1.0</td>
<td>0.125000</td>
<td>0.291667</td>
<td>0.60625</td>
<td>0.297917</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>11.590964</td>
<td>11.582443</td>
<td>31.584429</td>
<td>1.115393</td>
<td>2.097681</td>
<td>0.753373</td>
<td>160.847862</td>
<td>0.0</td>
<td>0.331064</td>
<td>0.455004</td>
<td>0.48909</td>
<td>0.457820</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-12" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bank_df[y<span class="op">==</span><span class="dv">0</span>].describe().loc[[<span class="st">'mean'</span>, <span class="st">'std'</span>],:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">CCAvg</th>
<th data-quarto-table-cell-role="th">Education</th>
<th data-quarto-table-cell-role="th">Mortgage</th>
<th data-quarto-table-cell-role="th">Personal Loan</th>
<th data-quarto-table-cell-role="th">Securities Account</th>
<th data-quarto-table-cell-role="th">CD Account</th>
<th data-quarto-table-cell-role="th">Online</th>
<th data-quarto-table-cell-role="th">CreditCard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>45.367257</td>
<td>20.132301</td>
<td>66.237389</td>
<td>2.373451</td>
<td>1.729009</td>
<td>1.843584</td>
<td>51.789381</td>
<td>0.0</td>
<td>0.102212</td>
<td>0.035841</td>
<td>0.595796</td>
<td>0.293584</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>11.450427</td>
<td>11.456672</td>
<td>40.578534</td>
<td>1.148771</td>
<td>1.567647</td>
<td>0.839975</td>
<td>92.038931</td>
<td>0.0</td>
<td>0.302961</td>
<td>0.185913</td>
<td>0.490792</td>
<td>0.455454</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>For the predictor “income” the mean is much higher for acceptors than for nonacceptors. Similarly for “CCAverage” and “Mortgage,” the mean is higher for acceptors than for nonacceptors.</p>
<p>Categorical predictors: “acceptors” are more likely to have higher level degrees (Education levels 2 and 3, graduate and professional), and more likely to have CD accounts.</p>
</section>
<section id="problem-12.1.b" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.b">Problem 12.1.b</h2>
<p>Examine the model performance on the validation set. ## Problem 12.1.b.i What is the accuracy rate?</p>
<div id="cell-15" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>classificationSummary(valid_y, da_class.predict(valid_X))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9480)

       Prediction
Actual    0    1
     0 1777   30
     1   74  119</code></pre>
</div>
</div>
<p>The accuracy of the discriminant analysis model is 94.8%.</p>
</section>
<section id="problem-12.1.b.ii" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.b.ii">Problem 12.1.b.ii</h2>
<p>Is one type of misclassification more likely than the other?</p>
<p>Yes - the number of cases of actual acceptors classified as nonacceptors is much higher than the number of cases of nonacceptors classified as acceptors.</p>
</section>
<section id="problem-12.1.b.iii" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.b.iii">Problem 12.1.b.iii</h2>
<p>Select three customers who were misclassified as <em>acceptors</em> and three who were misclassified as <em>nonacceptors</em>. The goal is to determine why they are misclassified. First, examine their probability of being classified as acceptors: is it close to the threshold of 0.5? If not, compare their predictor values to the summary statistics of the two classes to determine why they were misclassified.</p>
<div id="cell-17" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combine valid_X with actual value (valid_y) and predicted probability</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>success_probability <span class="op">=</span> da_class.predict_proba(valid_X)[:,<span class="dv">1</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>mergedData <span class="op">=</span> pd.concat(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        valid_X, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        pd.DataFrame({<span class="st">'actual'</span>: valid_y}, index<span class="op">=</span>valid_X.index),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        pd.DataFrame({<span class="st">'prob'</span>: success_probability}, index<span class="op">=</span>valid_X.index),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    ], axis<span class="op">=</span><span class="dv">1</span>, ignore_index<span class="op">=</span><span class="va">False</span>, sort<span class="op">=</span><span class="va">False</span>)  </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>mergedData <span class="op">=</span> mergedData.sort_values(by<span class="op">=</span><span class="st">'prob'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># loan acceptors misclassified as non-acceptors</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>mis_acceptors <span class="op">=</span> mergedData[mergedData.actual <span class="op">==</span> <span class="dv">1</span>].head(<span class="dv">3</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>mis_acceptors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">CCAvg</th>
<th data-quarto-table-cell-role="th">Mortgage</th>
<th data-quarto-table-cell-role="th">Securities Account</th>
<th data-quarto-table-cell-role="th">CD Account</th>
<th data-quarto-table-cell-role="th">Online</th>
<th data-quarto-table-cell-role="th">CreditCard</th>
<th data-quarto-table-cell-role="th">Education_2</th>
<th data-quarto-table-cell-role="th">Education_3</th>
<th data-quarto-table-cell-role="th">actual</th>
<th data-quarto-table-cell-role="th">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1577</td>
<td>34</td>
<td>8</td>
<td>65</td>
<td>1</td>
<td>3.0</td>
<td>227</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.000263</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">349</td>
<td>26</td>
<td>2</td>
<td>60</td>
<td>2</td>
<td>3.0</td>
<td>132</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.000602</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2158</td>
<td>50</td>
<td>25</td>
<td>83</td>
<td>4</td>
<td>3.1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.003128</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The probabilities are less than 0.5, many not even close to that threshold. Looking at customer ID 1577, we can see that their profile is similar to that of a nonacceptor. They have few existing lines of business with the bank (no securities account, no CD account, no credit card.). This is a case of the customer not behaving in the way that similar customers behave.</p>
<div id="cell-19" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loan nonacceptors misclassified as acceptors</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>mis_nonacceptors <span class="op">=</span> mergedData[mergedData.actual <span class="op">==</span> <span class="dv">0</span>].tail(<span class="dv">3</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>mis_nonacceptors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Income</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">CCAvg</th>
<th data-quarto-table-cell-role="th">Mortgage</th>
<th data-quarto-table-cell-role="th">Securities Account</th>
<th data-quarto-table-cell-role="th">CD Account</th>
<th data-quarto-table-cell-role="th">Online</th>
<th data-quarto-table-cell-role="th">CreditCard</th>
<th data-quarto-table-cell-role="th">Education_2</th>
<th data-quarto-table-cell-role="th">Education_3</th>
<th data-quarto-table-cell-role="th">actual</th>
<th data-quarto-table-cell-role="th">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4937</td>
<td>33</td>
<td>8</td>
<td>162</td>
<td>1</td>
<td>8.6</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.980754</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">785</td>
<td>46</td>
<td>22</td>
<td>164</td>
<td>2</td>
<td>7.6</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.990423</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2305</td>
<td>32</td>
<td>7</td>
<td>185</td>
<td>2</td>
<td>6.7</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.995511</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Probabilities are greater than 0.5, and not close to the threshold. Looking at the customer for ID 2305, we see that he has the demographic profile of an acceptor for most relevant variables (income, ccaverage). He is missing some of the “doing business with the bank already” attributes (Securities Acccount), but, overall, the customer profile is that of an acceptor, so it is a case of the customer not behaving in the way that similar customers behave.</p>
</section>
<section id="problem-12.1.c" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.c">Problem 12.1.c</h2>
<p>As in many marketing campaigns, it is more important to identify customers who will accept the offer rather than customers who will not accept it. Therefore, a good model should be especially accurate at detecting acceptors. Examine the lift chart and decile-wise lift chart for the validation set and interpret them in light of this ranking goal.</p>
<div id="cell-21" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>proba <span class="op">=</span> da_class.predict_proba(valid_X)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: valid_y, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> proba],</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> proba],</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'predicted'</span>: da_class.predict(valid_X) })</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, ax<span class="op">=</span>axes[<span class="dv">0</span>])</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Cumulative Gains'</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'#cases'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Cumulative Gains Chart'</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> liftChart(result.actual, ax<span class="op">=</span>axes[<span class="dv">1</span>], labelBars<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-12-ProbSolutions-DA_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Using the lift chart we can descend through the customers in order of probability of being a loan acceptor, knowing at each point how effective we have been in “skimming the cream” (acceptors). The decile chart is similar, differing only in that it proceeds in chunks of 10% of the data. From the decile chart we can see that taking the 10% of the records that are ranked by the model as “most probable acceptors” yields 7.5 times as many “acceptors” as would simply selecting 10% of the records at random.</p>
</section>
<section id="problem-12.1.d" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.d">Problem 12.1.d</h2>
<p>Compare the results from the discriminant analysis with those from a logistic regression (both with cutoff 0.5 and the same predictors). Examine the confusion matrices, the lift charts, and the decile charts. Which method performs better on your validation set in detecting the acceptors?</p>
<p>We can take the confusion matrix from the logistic regression model in chapter 10.</p>
<pre><code>Confusion Matrix (Accuracy 0.9595)

       Prediction
Actual    0    1
     0 1791   16
     1   65  128</code></pre>
<p>Discriminant analysis correctly classifies 115 of the acceptors, logistic regression 128. Therefore the logistic regression’s error rate in detecting acceptors is lower than that of discriminant analysis.</p>
<p>Decile chart of logistic regression: taking 10% of the records that are ranked by the model as “most probable acceptors” yields 7.8 times as many “acceptors” as would simply selecting 10% of the records at random. Decile chart of discriminant analysis: taking 10% of the records that are ranked by the model as “most probable acceptors” yields 7.5 times as many “acceptors” as would simply selecting 10% of the records at random. Therefore logistic regression performs slightly better than discriminant analysis in detecting acceptors for validation data.</p>
</section>
<section id="problem-12.1.e" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.e">Problem 12.1.e</h2>
<p>The bank is planning to continue its campaign by sending its offer to 1000 additional customers. Suppose that the cost of sending the offer is \$1 and the profit from an accepted offer is \$50. What is the expected profitability of this campaign?</p>
<div id="cell-24" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_y.value_counts())</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'probability of accepting the loan'</span>, <span class="dv">287</span> <span class="op">/</span> (<span class="dv">287</span> <span class="op">+</span> <span class="dv">2713</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'expected profitability '</span>, <span class="dv">96</span> <span class="op">*</span> <span class="dv">50</span> <span class="op">-</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    2713
1     287
Name: Personal Loan, dtype: int64
probability of accepting the loan 0.09566666666666666
expected profitability  3800</code></pre>
</div>
</div>
<p>The probability of acceptance of a loan = 0.0957 (prior class probability). Out of 1000 customers 9.57% (that is 96) can be expected to accept the loan offer.</p>
<p>Profit from each accepted offer = $50.</p>
<p>Total expected profitability is:</p>
<p>profit from these 101 customers - the cost of sending an offer.</p>
<p>Therefore total expected profitability = 96*50 - 1000 = 3800</p>
<p>Expected profitability from this campaign is \$3850.</p>
</section>
<section id="problem-12.1.f" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.1.f">Problem 12.1.f</h2>
<p>The cost of misclassifying a loan acceptor customer as a nonacceptor is much higher than the opposite misclassification cost. To minimize the expected cost of misclassification, should the cutoff value for classification (which is currently at 0.5) be increased or decreased?</p>
<p>If the cutoff were lowered, then we would classify more “non acceptors” cases as “acceptors” cases (more zeros misclassified as 1).</p>
<p>This means that the numerator in the classification error rate for truly completed will be less than or equal to b. Therefore, lowering the cutoff will lead to a reduced (or equal) classification error rate for truly acceptor cases.</p>
<p>Therefore, if the cutoff is lowered, then</p>
<ol type="1">
<li>It will classify more nonacceptors as acceptors.</li>
<li>It will minimize the expected cost of misclassification.</li>
</ol>
</section>
</section>
<section id="problem-12.2-identifying-good-system-administrators" class="level1">
<h1>Problem 12.2: Identifying Good System Administrators</h1>
<p>A management consultant is studying the roles played by experience and training in a system administrator’s ability to complete a set of tasks in a specified amount of time. In particular, she is interested in discriminating between administrators who are able to complete given tasks within a specified time and those who are not. Data are collected on the performance of 75 randomly selected administrators. They are stored in the file <em>SystemAdministrators.csv</em>.</p>
<p>Using these data, the consultant performs a discriminant analysis. The variable Experience measures months of full time system administrator experience, while Training measures number of relevant training credits. The dependent variable Completed is either <em>Yes</em> or <em>No</em>, according to whether or not the administrator completed the tasks.</p>
<div id="cell-27" class="cell" data-scrolled="true" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'SystemAdministrators.csv'</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Experience</th>
<th data-quarto-table-cell-role="th">Training</th>
<th data-quarto-table-cell-role="th">Completed task</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10.9</td>
<td>4</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>9.9</td>
<td>4</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>10.4</td>
<td>6</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>13.7</td>
<td>6</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>9.4</td>
<td>8</td>
<td>Yes</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="problem-12.2.a" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.2.a">Problem 12.2.a</h2>
<p>Create a scatter plot of Experience vs.&nbsp;Training using color or symbol to differentiate administrators who completed the tasks from those who did not complete them. See if you can identify a line that separates the two classes with minimum misclassification.</p>
<div id="cell-29" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> data[data[<span class="st">'Completed task'</span>] <span class="op">==</span> <span class="st">'Yes'</span>].plot.scatter(x<span class="op">=</span><span class="st">'Training'</span>, y<span class="op">=</span><span class="st">'Experience'</span>, c<span class="op">=</span><span class="st">'none'</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                                                        facecolors<span class="op">=</span><span class="st">'none'</span>, edgecolors<span class="op">=</span><span class="st">'C0'</span>, s<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>data[data[<span class="st">'Completed task'</span>] <span class="op">==</span> <span class="st">'No'</span>].plot.scatter(x<span class="op">=</span><span class="st">'Training'</span>, y<span class="op">=</span><span class="st">'Experience'</span>, c<span class="op">=</span><span class="st">'none'</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                                                  facecolors<span class="op">=</span><span class="st">'none'</span>, edgecolors<span class="op">=</span><span class="st">'C1'</span>, s<span class="op">=</span><span class="dv">10</span>, ax<span class="op">=</span>ax)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-12-ProbSolutions-DA_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the scatterplot we can observe that programmers who completed the task tend to have more experience. Training, however, does not play much a role in task completion. Therefore, the predictor Experience appears more useful for classifying task completion.</p>
</section>
<section id="problem-12.2.b" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.2.b">Problem 12.2.b</h2>
<p>Run a discriminant analysis with both predictors using the entire dataset as training data. Among those who completed the tasks, what is the percentage of administrators who are classified incorrectly as failing to complete the tasks?</p>
<div id="cell-31" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="op">=</span> [<span class="st">'Training'</span>, <span class="st">'Experience'</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>outcome <span class="op">=</span> <span class="st">'Completed task'</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data[predictors]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data[outcome]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>da <span class="op">=</span> LinearDiscriminantAnalysis()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>da.fit(X, y)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>classificationSummary(y, da.predict(X))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9067)

       Prediction
Actual  0  1
     0 58  2
     1  5 10</code></pre>
</div>
</div>
<p>Among 15 administrators who completed the task, 5 are misclassified as failing to complete the task.</p>
<p>Therefore, the percentage of administrators who completed the task but were misclassified as failing to complete the task is 33.33%.</p>
</section>
<section id="problem-12.2.c" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.2.c">Problem 12.2.c</h2>
<p>Compute the two classification scores for an administrator with 4 months of experience and six credits of training. Based on these, how would you classify this administrator?</p>
<div id="cell-33" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>admin <span class="op">=</span> pd.DataFrame([{<span class="st">'Training'</span>: <span class="fl">6.0</span>, <span class="st">'Experience'</span>: <span class="dv">4</span>}])</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(da.predict(admin[predictors]))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>da.predict_proba(admin[predictors])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['No']</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>array([[9.99052428e-01, 9.47571894e-04]])</code></pre>
</div>
</div>
<p>The classification score for class “No” is more than that for class “Yes”. Therefore, we classify the administrator as “fail to complete the task.”</p>
</section>
<section id="problem-12.2.d" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.2.d">Problem 12.2.d</h2>
<p>How much experience must be accumulated by an administrator with four training credits before his or her estimated probability of completing the tasks exceeds 0.5?</p>
<div id="cell-35" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> experience <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>, <span class="dv">14</span>):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    admin <span class="op">=</span> pd.DataFrame([{<span class="st">'Training'</span>: <span class="dv">4</span>, <span class="st">'Experience'</span>: experience}])</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Experience </span><span class="sc">{</span>experience<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>da<span class="sc">.</span>predict_proba(admin[predictors])[<span class="dv">0</span>][<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Experience 3: 0.000
Experience 4: 0.001
Experience 5: 0.003
Experience 6: 0.013
Experience 7: 0.051
Experience 8: 0.187
Experience 9: 0.494
Experience 10: 0.805
Experience 11: 0.946
Experience 12: 0.987
Experience 13: 0.997</code></pre>
</div>
</div>
<p>he administrator must accumulate more than 9 years experience with 4 training credits so that his/her estimated probability of completing the task exceeds 0.5.</p>
</section>
<section id="problem-12.2.e" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.2.e">Problem 12.2.e</h2>
<p>Compare the classification accuracy of this model to that resulting from a logistic regression with cutoff 0.5.</p>
<div id="cell-37" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="op">=</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"l2"</span>, C<span class="op">=</span><span class="fl">1e42</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>logit_reg.fit(X, y)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>classificationSummary(y, logit_reg.predict(X))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.9067)

       Prediction
Actual  0  1
     0 58  2
     1  5 10</code></pre>
</div>
</div>
<p>Among 15 administrators who completed task, 5 are misclassified as failing to complete the task. Therefore percentage of administrators who completed the task but were misclassified as failing to complete the task is 33.33%.</p>
<p>Therefore, the results from both discriminant analysis and logistic regression are the same.</p>
</section>
</section>
<section id="problem-12.3-detecting-spam-e-mail-from-the-uci-machine-learning-repository" class="level1">
<h1>Problem 12.3: Detecting Spam E-mail (from the UCI Machine Learning Repository)</h1>
<p>A team at Hewlett-Packard collected data on a large number of e-mail messages from their postmaster and personal e-mail for the purpose of finding a classifier that can separate e-mail messages that are <em>spam</em> vs.&nbsp;<em>nonspam</em> (a.k.a. ‘ham’). The spam concept is diverse: It includes advertisements for products or websites, ‘make money fast’ schemes, chain letters, pornography, and so on. The definition used here is ‘unsolicited commercial e-mail.’ The file <em>Spambase.csv</em> contains information on 4601 e-mail messages, among which 1813 are tagged ‘spam.’ The predictors include 57 attributes, most of them are the average number of times a certain word (e.g., mail, George) or symbol (e.g., #, !) appears in the e-mail. A few predictors are related to the number and length of capitalized words.</p>
<section id="problem-12.3.a" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.3.a">Problem 12.3.a</h2>
<p>To reduce the number of predictors to a manageable size, examine how each predictor differs between the <em>spam</em> and <em>nonspam</em> e-mails by comparing the spam-class average and nonspam-class average. Which are the 11 predictors that appear to vary the most between <em>spam</em> and <em>nonspam</em> e-mails? From these 11, which words or signs occur more often in spam?</p>
<div id="cell-40" class="cell" data-scrolled="false" data-execution_count="20">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">'Spambase.csv'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>data.head()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>data.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>Index(['make', 'address', 'all', 'W_3d', 'our', 'over', 'remove', 'internet',
       'order', 'mail', 'receive', 'will ', 'people', 'report', 'addresses',
       'free', 'business', 'email', 'you ', 'credit', 'your', 'font', 'W_000',
       'money', 'hp', 'hpl', 'george', 'W_650', 'lab', 'labs', 'telnet',
       'W_857', 'data', 'W_415', 'W_85', 'technology', 'W_1999', 'parts', 'pm',
       'direct', 'cs', 'meeting', 'original', 'project ', 're:', 'edu',
       'table ', 'conference', 'C;', 'C(', 'C[', 'C!', 'C$', 'C#', 'CAP_avg',
       'CAP_long', 'CAP_tot', 'Spam'],
      dtype='object')</code></pre>
</div>
</div>
<div id="cell-41" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>spamData <span class="op">=</span> data[data.Spam <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>nonspamData <span class="op">=</span> data[data.Spam <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># determine absolute difference between spam-class average and nonspam-class average for each of the variables</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>difference <span class="op">=</span> spamData.mean() <span class="op">-</span> nonspamData.mean()</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(difference.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">9</span>))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>absDifference <span class="op">=</span> <span class="bu">abs</span>(difference)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the 10 values with the largest absolute difference in mean</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>absDifference.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CAP_tot     309.148468
CAP_long     86.178780
CAP_avg       7.141864
Spam          1.000000
you           0.994199
your          0.941668
free          0.444775
C!            0.403729
our           0.332915
dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>CAP_tot     309.148468
CAP_long     86.178780
CAP_avg       7.141864
george        1.263716
Spam          1.000000
you           0.994199
your          0.941668
hp            0.877994
free          0.444775
hpl           0.422822
C!            0.403729
our           0.332915
dtype: float64</code></pre>
</div>
</div>
<p>The following 11 predictors appear to vary most between spam and non-spam. &gt; our, C!, hpl, free, hp, your, you, george, CAP_avg, CAP_long, CAP_tot</p>
<p>Which of these occur more often in spam? &gt; our, C!, free, your, you, CAP_avg, CAP_long, CAP_tot</p>
</section>
<section id="problem-12.3.b" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.3.b">Problem 12.3.b</h2>
<p>Partition the data into training and validation sets, then perform a discriminant analysis on the training data using only the 11 predictors.</p>
<div id="cell-43" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="op">=</span> [<span class="st">'our'</span>, <span class="st">'C!'</span>, <span class="st">'hpl'</span>, <span class="st">'free'</span>, <span class="st">'hp'</span>, <span class="st">'your'</span>, <span class="st">'you '</span>, <span class="st">'george'</span>, <span class="st">'CAP_avg'</span>, <span class="st">'CAP_long'</span>, <span class="st">'CAP_tot'</span>]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>outcome <span class="op">=</span> <span class="st">'Spam'</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create training and validation sets</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data[predictors]</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data[outcome]</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>train_X, valid_X, train_y, valid_y <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Training set:'</span>, train_X.shape, <span class="st">'Validation set:'</span>, valid_X.shape)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>da_class <span class="op">=</span> LinearDiscriminantAnalysis()</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>da_class.fit(train_X, train_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set: (2760, 11) Validation set: (1841, 11)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)</code></pre>
</div>
</div>
</section>
<section id="problem-12.3.c" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.3.c">Problem 12.3.c</h2>
<p>If we are interested mainly in detecting spam messages, is this model useful? Use the confusion matrix, lift chart, and decile chart for the validation set for the evaluation.</p>
<div id="cell-45" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>classificationSummary(valid_y, da_class.predict(valid_X))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="dv">239</span> <span class="op">+</span> <span class="dv">504</span><span class="sc">}</span><span class="ss"> spam message, error rate </span><span class="sc">{</span><span class="dv">239</span> <span class="op">/</span> (<span class="dv">504</span> <span class="op">+</span> <span class="dv">239</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.8332)

       Prediction
Actual    0    1
     0 1030   68
     1  239  504
743 spam message, error rate 32.17</code></pre>
</div>
</div>
<p>Among the 743 spam messages, 239 are misclassified as non-spam. Therefore the error rate is 32.17%, which is moderately high.</p>
<div id="cell-47" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>proba <span class="op">=</span> da_class.predict_proba(valid_X)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: valid_y, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'p(0)'</span>: [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> proba],</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'p(1)'</span>: [p[<span class="dv">1</span>] <span class="cf">for</span> p <span class="kw">in</span> proba],</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'predicted'</span>: da_class.predict(valid_X) })</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> result.sort_values(by<span class="op">=</span>[<span class="st">'p(1)'</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> gainsChart(result.actual, ax<span class="op">=</span>axes[<span class="dv">0</span>])</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Cumulative Gains'</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'#cases'</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Cumulative Gains Chart'</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> liftChart(result.actual, ax<span class="op">=</span>axes[<span class="dv">1</span>], labelBars<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch-12-ProbSolutions-DA_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the decile chart: if we take 10% of the records that are ranked by the model as “most probable spam”, it captures 2.3 times more “spam” messages than simply selecting 10% of the records at random.</p>
</section>
<section id="problem-12.3.d" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.3.d">Problem 12.3.d</h2>
<p>In the sample, almost 40% of the e-mail messages were tagged as spam. However, suppose that the actual proportion of spam messages in these e-mail accounts is 10%. Compute the constants of the classification functions to account for this information.</p>
<p>The constant in the classification function of <code>da_class</code> is given as:</p>
<div id="cell-51" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'The constant of the classification function is: </span><span class="sc">{</span>da_class<span class="sc">.</span>intercept_<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'The priors of the classification function are: </span><span class="sc">{</span>da_class<span class="sc">.</span>priors_<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The constant of the classification function is: [-2.07053468]
The priors of the classification function are: [0.61231884 0.38768116]</code></pre>
</div>
</div>
<p>If we want to calculate the constant for a different prior, we need to determine first the log-differences in the priors and then adjust the constant.</p>
<div id="cell-53" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>log_priors <span class="op">=</span> np.log(da_class.priors_)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>log_priors_10 <span class="op">=</span> np.log([<span class="fl">0.9</span>, <span class="fl">0.1</span>])</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>diff_log_priors <span class="op">=</span> log_priors[<span class="dv">1</span>] <span class="op">-</span> log_priors[<span class="dv">0</span>]</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>diff_log_priors_10 <span class="op">=</span> log_priors_10[<span class="dv">1</span>] <span class="op">-</span> log_priors_10[<span class="dv">0</span>]</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Difference of log-prior of classification function: </span><span class="sc">{</span>diff_log_priors<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Difference of log-prior of classification function for new priors: </span><span class="sc">{</span>diff_log_priors_10<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>adjusted_intercept <span class="op">=</span> da_class.intercept_ <span class="op">-</span> diff_log_priors <span class="op">+</span> diff_log_priors_10</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Adjusted intercept for new priors: </span><span class="sc">{</span>adjusted_intercept<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Difference of log-prior of classification function: -0.45706988046116737
Difference of log-prior of classification function for new priors: -2.197224577336219
Adjusted intercept for new priors: [-3.81068937]</code></pre>
</div>
</div>
<p>The <code>LinearDiscriminantAnalysis</code> implementation in <em>scikit-learn</em> allows specifying the priors directly. We can confirm the correctness of our calculation above using this.</p>
<div id="cell-55" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>da_class_10 <span class="op">=</span> LinearDiscriminantAnalysis(priors <span class="op">=</span> [<span class="fl">0.9</span>, <span class="fl">0.1</span>])</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>da_class_10.fit(train_X, train_y)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>classificationSummary(valid_y, da_class_10.predict(valid_X))</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(da_class_10.intercept_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.6594)

       Prediction
Actual    0    1
     0 1086   12
     1  615  128
[-3.81068937]</code></pre>
</div>
</div>
</section>
<section id="problem-12.3.e" class="level2">
<h2 class="anchored" data-anchor-id="problem-12.3.e">Problem 12.3.e</h2>
<p>A spam filter that is based on your model is used, so that only messages that are classified as <em>nonspam</em> are delivered, while messages that are classified as <em>spam</em> are quarantined. In this case, misclassifying a nonspam e-mail (as spam) has much heftier results. Suppose that the cost of quarantining a nonspam e-mail is 20 times that of not detecting a spam message. Compute the constants of the classification functions to account for these costs (assume that the proportion of spam is reflected correctly by the sample proportion).</p>
<div id="cell-57" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>log_priors <span class="op">=</span> np.log(da_class.priors_)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>diff_log_priors <span class="op">=</span> log_priors[<span class="dv">1</span>] <span class="op">-</span> log_priors[<span class="dv">0</span>]</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Difference of log-prior of classification function: </span><span class="sc">{</span>diff_log_priors<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust intercept using the log of the cost-ratio</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>adjusted_intercept <span class="op">=</span> da_class.intercept_ <span class="op">-</span> np.log(<span class="dv">20</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Intercept before adjustment </span><span class="sc">{</span>da_class<span class="sc">.</span>intercept_<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Adjusted intercept including cost: </span><span class="sc">{</span>adjusted_intercept<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Difference of log-prior of classification function: -0.45706988046116737
Intercept before adjustment [-2.07053468]
Adjusted intercept including cost: [-5.06626695]</code></pre>
</div>
</div>
<p>For the <code>LinearDiscriminantAnalysis</code> implementation in <em>scikit-learn</em> it is better to adjust the priors to take the misclassification costs into account.</p>
<div id="cell-59" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ratio of costs (q1/q2): </span><span class="sc">{</span>K<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>priorNonspam <span class="op">=</span> da_class.priors_[<span class="dv">0</span>]</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>priorSpam <span class="op">=</span> da_class.priors_[<span class="dv">1</span>]</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>adjPriorNonspam <span class="op">=</span> priorNonspam <span class="op">*</span> K <span class="op">/</span> (priorNonspam <span class="op">*</span> K <span class="op">+</span> priorSpam)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>adjPriorSpam <span class="op">=</span> priorSpam <span class="op">/</span> (priorNonspam <span class="op">*</span> K <span class="op">+</span> priorSpam)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Adjusted prior of nonspam: </span><span class="sc">{</span>adjPriorNonspam<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Adjusted prior of spam: </span><span class="sc">{</span>adjPriorSpam<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ratio of costs (q1/q2): 20
Adjusted prior of nonspam: 0.9693145970748495
Adjusted prior of spam: 0.03068540292515056</code></pre>
</div>
</div>
<div id="cell-60" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>da_class_spam <span class="op">=</span> LinearDiscriminantAnalysis(priors <span class="op">=</span> [adjPriorNonspam, adjPriorSpam])</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>da_class_spam.fit(train_X, train_y)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>classificationSummary(valid_y, da_class_spam.predict(valid_X))</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>da_class_spam.intercept_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix (Accuracy 0.6122)

       Prediction
Actual    0    1
     0 1092    6
     1  708   35</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>array([-5.06626695])</code></pre>
</div>
</div>
<p>We can see that adjusting the priors leads to a model which predicts fewer <em>nonspam</em> messages as <em>spam</em>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>